import {test,expect,type Page} from '@playwright/test';
const key='ggl_customization_v1';
async function panel(page:Page,section:string){await page.getByRole('button',{name:'Customize lounge'}).click();await page.getByRole('navigation',{name:'Customization sections'}).getByRole('button',{name:section,exact:true}).click();}
async function png(page:Page){return Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=24;const g=c.getContext('2d')!;g.fillStyle='#7957cc';g.fillRect(0,0,24,24);return c.toDataURL('image/png').split(',')[1];}),'base64');}
async function saved(page:Page){return page.evaluate(k=>JSON.parse(localStorage.getItem(k)||'{}'),key);}

test('custom theme persists across reload and other pages',async({page})=>{await page.goto('/');await panel(page,'Themes');await page.getByRole('button',{name:'Cyberpunk',exact:true}).click();await expect.poll(async()=> (await saved(page)).theme?.preset).toBe('cyber');await page.getByLabel('Accent color',{exact:true}).fill('#44ccaa');await page.getByRole('button',{name:'Done',exact:true}).click();await page.reload();await expect.poll(()=>page.evaluate(()=>document.documentElement.style.getPropertyValue('--lime'))).toBe('#44ccaa');await page.goto('/apps');await expect.poll(()=>page.evaluate(()=>document.documentElement.style.getPropertyValue('--lime'))).toBe('#44ccaa');});

test('tab name and favicon persist and restore when disabled',async({page})=>{await page.goto('/');await panel(page,'Tab cloak');await page.getByLabel('Tab name',{exact:true}).fill('My chosen tab');await page.getByLabel('Favicon URL or emoji',{exact:true}).fill('🌱');await page.getByRole('button',{name:'Apply favicon'}).click();await page.getByRole('switch',{name:'Enable tab cloaking'}).check();await expect(page).toHaveTitle('My chosen tab');expect(await page.locator('head link[rel="icon"]').first().getAttribute('href')).toMatch(/^data:image\/svg/);await page.getByRole('button',{name:'Done',exact:true}).click();await page.goto('/apps');await expect(page).toHaveTitle('My chosen tab');await panel(page,'Tab cloak');await page.getByRole('switch',{name:'Enable tab cloaking'}).uncheck();await expect(page).not.toHaveTitle('My chosen tab');});

test('background image is stored locally and survives reload',async({page})=>{await page.goto('/');await panel(page,'Background');await page.getByLabel('Upload background',{exact:true}).setInputFiles({name:'personal.png',mimeType:'image/png',buffer:await png(page)});await expect(page.getByText('personal.png',{exact:true})).toBeVisible();await expect.poll(async()=> (await saved(page)).background?.preset).toBe('upload');await page.getByRole('button',{name:'Done',exact:true}).click();await page.reload();await expect.poll(()=>page.locator('.gg-wallpaper img').evaluate((img:HTMLImageElement)=>img.complete&&img.naturalWidth>0)).toBe(true);expect((await saved(page)).background.mediaName).toBe('personal.png');});

test('preset video really plays, muted and looping',async({page})=>{await page.goto('/');await panel(page,'Background');await page.getByRole('button',{name:'Aurora · video',exact:true}).click();await expect.poll(()=>page.getByTestId('background-video').evaluate((v:HTMLVideoElement)=>v.readyState>=2&&v.currentTime>0&&!v.paused)).toBe(true);expect(await page.getByTestId('background-video').evaluate((v:HTMLVideoElement)=>v.muted&&v.loop)).toBe(true);});

test('uploaded video also persists with its bytes, not a dead blob URL',async({page})=>{await page.goto('/');await panel(page,'Background');await page.getByLabel('Upload background',{exact:true}).setInputFiles('public/backgrounds/orbit.webm');await expect(page.getByText('orbit.webm',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Done',exact:true}).click();await page.reload();await expect.poll(()=>page.getByTestId('background-video').evaluate((v:HTMLVideoElement)=>v.videoWidth>0&&v.currentTime>0)).toBe(true);});

test('invalid upload is rejected without replacing the current background',async({page})=>{await page.goto('/');await panel(page,'Background');await page.getByRole('button',{name:'Sunset',exact:true}).click();await page.getByLabel('Upload background',{exact:true}).setInputFiles({name:'not-a-photo.png',mimeType:'image/png',buffer:Buffer.from('not an image')});await expect(page.getByRole('dialog').getByRole('alert')).toContainText(/cannot decode|could not/);expect((await saved(page)).background.preset).toBe('sunset');});

test('custom cursor applies to the site and is persisted',async({page})=>{await page.goto('/');await panel(page,'Cursor');await page.getByRole('button',{name:'Neon ring',exact:true}).click();await expect.poll(()=>page.evaluate(()=>getComputedStyle(document.body).cursor)).toContain('data:image/svg+xml');await page.getByLabel('Upload cursor',{exact:true}).setInputFiles({name:'pointer.png',mimeType:'image/png',buffer:await png(page)});await expect.poll(async()=> (await saved(page)).cursor?.preset).toBe('custom');await page.reload();await expect.poll(()=>page.evaluate(()=>getComputedStyle(document.body).cursor)).toContain('data:image/png');});

test('key-sensitive background reacts but never to text-field typing',async({page})=>{await page.goto('/');await panel(page,'Key effects');await page.getByRole('switch',{name:'Key-sensitive background'}).check();await page.getByRole('button',{name:'Done',exact:true}).click();await page.keyboard.press('KeyA');await expect.poll(()=>page.getByTestId('reactive-background').getAttribute('data-pulses')).not.toBeNull();const count=await page.getByTestId('reactive-background').getAttribute('data-pulses');const search=page.locator('input[placeholder*="Search"]').first();await search.click();await page.keyboard.type('hello');expect(await page.getByTestId('reactive-background').getAttribute('data-pulses')).toBe(count);});

test('recorded panic key redirects from a focused game iframe',async({page})=>{await page.route('**/panic-proof',route=>route.fulfill({contentType:'text/html',body:'<h1>Panic destination reached</h1>'}));await page.goto('/?play=2048');await expect(page.locator('iframe.game-frame')).toBeVisible();await panel(page,'Panic key');await page.getByRole('button',{name:'Record a key'}).click();await expect(page.getByRole('status').filter({hasText:'Press a key'})).toBeVisible();await page.keyboard.press('KeyQ');await page.getByLabel('Panic destination',{exact:true}).fill('/panic-proof');await page.getByRole('button',{name:'Save destination'}).click();await page.getByRole('switch',{name:'Enable panic shortcut'}).check();await page.getByRole('button',{name:'Done',exact:true}).click();await page.frameLocator('iframe.game-frame').locator('h1').click();await page.locator('iframe.game-frame').evaluate((frame:HTMLIFrameElement)=>frame.contentWindow!.addEventListener('beforeunload',e=>{e.preventDefault();e.returnValue='unsaved';}));await page.keyboard.press('KeyQ');await expect(page).toHaveURL(/\/panic-proof$/);await expect(page.getByRole('heading',{name:'Panic destination reached'})).toBeVisible();});

test('customization panel fits a mobile viewport',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');await panel(page,'Background');const bounds=await page.getByRole('dialog').boundingBox();expect(bounds!.x).toBeGreaterThanOrEqual(0);expect(bounds!.width).toBeLessThanOrEqual(390);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);});

test('panic recorder supports modifier combinations and Escape',async({page})=>{await page.goto('/');await panel(page,'Panic key');await page.getByRole('button',{name:'Record a key'}).click();await page.keyboard.press('Control+Shift+KeyK');await expect.poll(async()=> (await saved(page)).panic?.binding).toEqual({code:'KeyK',key:'K',ctrl:true,alt:false,shift:true,meta:false});await page.getByRole('button',{name:'Record a key'}).click();await page.keyboard.press('Escape');await expect.poll(async()=> (await saved(page)).panic?.binding.code).toBe('Escape');await expect(page.getByRole('dialog')).toBeVisible();});

test('cloaking and panic also work in a standalone local game tab',async({page})=>{await page.route('**/standalone-panic',r=>r.fulfill({contentType:'text/html',body:'<h1>Standalone panic reached</h1>'}));await page.goto('/');await expect.poll(async()=> (await saved(page)).version).toBe(1);await page.evaluate(k=>{const s=JSON.parse(localStorage.getItem(k)!);s.cloak={enabled:true,title:'Standalone workspace',icon:'🌿'};s.panic={enabled:true,destination:'/standalone-panic',whileTyping:false,binding:{code:'KeyQ',key:'q',ctrl:false,alt:false,meta:false,shift:false}};localStorage.setItem(k,JSON.stringify(s));},key);await page.goto('/games/2048/index.html');await expect(page).toHaveTitle('Standalone workspace');await page.evaluate(k=>{const s=JSON.parse(localStorage.getItem(k)!);s.cloak.enabled=false;localStorage.setItem(k,JSON.stringify(s));window.dispatchEvent(new StorageEvent('storage',{key:k}));},key);await expect(page).toHaveTitle('2048');await page.evaluate(()=>window.addEventListener('beforeunload',e=>{e.preventDefault();e.returnValue='unsaved';}));await page.locator('h1').click();await page.keyboard.press('KeyQ');await expect(page).toHaveURL(/standalone-panic$/);});

test('reduced motion pauses background videos',async({page})=>{await page.goto('/');await panel(page,'Background');await page.getByRole('button',{name:'Orbit · video',exact:true}).click();await expect.poll(()=>page.getByTestId('background-video').evaluate((v:HTMLVideoElement)=>v.currentTime>0)).toBe(true);await page.emulateMedia({reducedMotion:'reduce'});await expect.poll(()=>page.getByTestId('background-video').evaluate((v:HTMLVideoElement)=>v.paused)).toBe(true);});
