'use client'

import { useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { authClient } from '@/lib/auth-client'

const achievementNames: Record<string, string> = { '5m': 'Warm-Up Lap', '10m': 'Settled In', '30m': 'Arcade Regular', '45m': 'Deep Session', '1h': 'Lounge Legend', '2h': 'Night Shift', '5h': 'GG-LOUNGE Mythic', 'chat': 'Open Channel', 'note': 'Second Brain', 'tool': 'Utility Belt' }
const milestones = [{ slug: '5m', ms: 5 * 60_000 }, { slug: '10m', ms: 10 * 60_000 }, { slug: '30m', ms: 30 * 60_000 }, { slug: '45m', ms: 45 * 60_000 }, { slug: '1h', ms: 60 * 60_000 }, { slug: '2h', ms: 2 * 60 * 60_000 }, { slug: '5h', ms: 5 * 60 * 60_000 }]

export default function MemberPage() {
  const router = useRouter(); const session = authClient.useSession(); const [mode, setMode] = useState<'login'|'signup'>('login'); const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [data, setData] = useState<any>(null); const [message, setMessage] = useState(''); const [note, setNote] = useState(''); const [notice, setNotice] = useState('')
  useEffect(() => { if (!session.data?.user) return; const refresh = () => fetch('/api/member').then(r => r.ok ? r.json() : null).then(next => next && setData(next)).catch(() => undefined); refresh(); const interval = window.setInterval(refresh, 5000); return () => window.clearInterval(interval) }, [session.data?.user])
  useEffect(() => { if (!session.data?.user) return; const started = Date.now(); const timer = window.setInterval(() => { const elapsed = Date.now() - started; milestones.filter(m => elapsed >= m.ms && !(data?.achievements || []).some((a: any) => a.slug === m.slug)).forEach(m => { fetch('/api/member', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'achievement', slug: m.slug }) }); setNotice(`Achievement unlocked: ${achievementNames[m.slug]}`); setTimeout(() => setNotice(''), 5000) }) }, 10_000); return () => clearInterval(timer) }, [session.data?.user, data?.achievements])
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); const email = `${username.trim().toLowerCase().replace(/[^a-z0-9_-]/g, '')}@gg-lounge.local`; const result = mode === 'login' ? await authClient.signIn.email({ email, password }) : await authClient.signUp.email({ email, password, name: username }); setBusy(false); if (result.error) setNotice(result.error.message || 'Could not authenticate'); else router.refresh() }
  async function send(action: string, payload: object) { await fetch('/api/member', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, username, ...payload }) }); const next = await fetch('/api/member').then(r => r.json()); setData(next); setMessage(''); setNote(''); setNotice(action === 'chat' ? 'Message sent' : 'Saved') }
  if (!session.data?.user) return <main className="member-page"><a className="member-back" href="/">← Back to lounge</a><section className="auth-card"><p className="eyebrow">GG-LOUNGE MEMBERS</p><h1>{mode === 'login' ? 'Enter the lounge.' : 'Claim your handle.'}</h1><p>Username-only access to achievements, live chat, notes, and the tools desk.</p><form onSubmit={submit}><input required minLength={3} value={username} onChange={e => setUsername(e.target.value)} placeholder="Username" autoComplete="username" /><input required minLength={8} value={password} onChange={e => setPassword(e.target.value)} placeholder="Password" type="password" autoComplete={mode === 'login' ? 'current-password' : 'new-password'} /><button disabled={busy}>{busy ? 'Connecting…' : mode === 'login' ? 'Sign in' : 'Create account'}</button></form><button className="text-button" onClick={() => setMode(mode === 'login' ? 'signup' : 'login')}>{mode === 'login' ? 'New here? Create account' : 'Already have an account? Sign in'}</button><p className="guest-note">Guests can still play every game without signing in.</p>{notice && <p className="member-notice">{notice}</p>}</section></main>
  return <main className="member-page"><header className="member-header"><div><p className="eyebrow">GG-LOUNGE MEMBERS / {session.data.user.name}</p><h1>Your after-hours dashboard.</h1></div><div className="member-actions"><a href="/">Play games</a><button onClick={() => authClient.signOut().then(() => router.refresh())}>Sign out</button></div></header>{notice && <div className="achievement-toast"><span>NEW ACHIEVEMENT</span><strong>{notice}</strong></div>}<section className="member-grid"><article className="member-panel achievements"><div className="panel-heading"><span>ACHIEVEMENTS</span><strong>{data?.achievements?.length || 0} unlocked</strong></div><div className="achievement-list">{Object.entries(achievementNames).map(([slug, title]) => <div className={(data?.achievements || []).some((a: any) => a.slug === slug) ? 'achievement unlocked' : 'achievement'} key={slug}><span>{(data?.achievements || []).some((a: any) => a.slug === slug) ? '✦' : '○'}</span><div><strong>{title}</strong><small>{slug === 'chat' ? 'Send a chat message' : slug === 'note' ? 'Save your first note' : slug === 'tool' ? 'Use the tools desk' : `Stay in the lounge for ${slug}`}</small></div></div>)}</div></article><article className="member-panel chat"><div className="panel-heading"><span>LIVE CHAT</span><strong>Members only</strong></div><div className="chat-log">{(data?.messages || []).map((m: any) => <p key={m.id}><b>{m.username}</b> {m.body}</p>)}</div><form onSubmit={e => { e.preventDefault(); send('chat', { message }) }}><input value={message} onChange={e => setMessage(e.target.value)} placeholder="Say something…" maxLength={500} /><button>Send</button></form></article><article className="member-panel notes"><div className="panel-heading"><span>NOTES</span><strong>Saved to your account</strong></div><input value={note} onChange={e => setNote(e.target.value)} placeholder="Write a note…" /><button onClick={() => send('note', { title: 'Quick note', note })}>Save note</button><div className="saved-notes">{(data?.notes || []).map((n: any) => <p key={n.id}><b>{n.title}</b><br />{n.body}</p>)}</div></article><article className="member-panel tools"><div className="panel-heading"><span>TOOLS & APPS</span><strong>Open desk</strong></div><div className="tool-grid"><a href="/games/youtube/index.html">YouTube</a><button onClick={() => alert('Calculator ready: use your device calculator or add an expression here.')}>Calculator</button><button onClick={() => send('achievement', { slug: 'tool' })}>Timer</button><button onClick={() => send('achievement', { slug: 'tool' })}>Stopwatch</button><button onClick={() => navigator.clipboard?.writeText('#d7f34a')}>Color picker</button><button onClick={() => setNotice('Randomizer says: play something unexpected.')}>Randomizer</button></div></article></section></main>
}
