'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { authClient } from '@/lib/auth-client'

import { achievements } from '@/lib/achievements'
import { AchievementGallery } from '@/components/achievement-gallery'

export default function MemberPage() {
  const router = useRouter(); const session = authClient.useSession(); const [mode, setMode] = useState<'login'|'signup'>('login'); const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [data, setData] = useState<any>(null); const [message, setMessage] = useState(''); const [note, setNote] = useState(''); const [notice, setNotice] = useState('')
  useEffect(() => { if (!session.data?.user) return; const refresh = () => fetch('/api/member').then(r => r.ok ? r.json() : null).then(next => next && setData(next)).catch(() => undefined); refresh(); const interval = window.setInterval(refresh, 5000); return () => window.clearInterval(interval) }, [session.data?.user])
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); const email = `${username.trim().toLowerCase().replace(/[^a-z0-9_-]/g, '')}@gg-lounge.local`; const result = mode === 'login' ? await authClient.signIn.email({ email, password }) : await authClient.signUp.email({ email, password, name: username }); setBusy(false); if (result.error) setNotice(result.error.message || 'Could not authenticate'); else router.refresh() }
  async function send(action: string, payload: object) {
    try {
      const response = await fetch('/api/member', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, ...payload }) })
      const result = await response.json()
      if (!response.ok) { setNotice(result.error || 'Could not save. Try again.'); return }
      const next = await fetch('/api/member').then(r => { if (!r.ok) throw new Error(); return r.json() })
      setData(next); if (action === 'chat') setMessage(''); else setNote('')
      const earned = achievements.find(a => result.unlocked?.includes(a.slug))
      setNotice(earned ? `Achievement unlocked: ${earned.title}` : action === 'chat' ? 'Message sent' : 'Note saved')
    } catch { setNotice('Connection interrupted. Please try again.') }
  }
  if (!session.data?.user) return <main className="member-page"><a className="member-back" href="/">← Back to lounge</a><section className="auth-card"><p className="eyebrow">GG-LOUNGE MEMBERS</p><h1>{mode === 'login' ? 'Enter the lounge.' : 'Claim your handle.'}</h1><p>Username-only access to achievements, live chat, notes, and the tools desk.</p><form onSubmit={submit}><input required minLength={3} value={username} onChange={e => setUsername(e.target.value)} placeholder="Username" autoComplete="username" /><input required minLength={8} value={password} onChange={e => setPassword(e.target.value)} placeholder="Password" type="password" autoComplete={mode === 'login' ? 'current-password' : 'new-password'} /><button disabled={busy}>{busy ? 'Connecting…' : mode === 'login' ? 'Sign in' : 'Create account'}</button></form><button className="text-button" onClick={() => setMode(mode === 'login' ? 'signup' : 'login')}>{mode === 'login' ? 'New here? Create account' : 'Already have an account? Sign in'}</button><p className="guest-note">Guests can still play every game without signing in.</p>{notice && <p className="member-notice">{notice}</p>}</section></main>
  return <main className="member-page"><header className="member-header"><div><p className="eyebrow">GG-LOUNGE MEMBERS / {session.data.user.name}</p><h1>Your after-hours dashboard.</h1></div><div className="member-actions"><a href="/">Play games</a><a href="/tools">Tools & Apps</a><a href="/ai">AI Studio</a><button onClick={() => authClient.signOut().then(() => router.refresh())}>Sign out</button></div></header>{notice && <div className="achievement-toast"><span>LOUNGE UPDATE</span><strong>{notice}</strong></div>}<section className="member-grid"><article className="member-panel achievements"><div className="panel-heading"><span>REAL GAMEPLAY. REAL MILESTONES.</span></div><AchievementGallery slugs={(data?.achievements || []).map((a: { slug: string }) => a.slug)} /></article><article className="member-panel chat"><div className="panel-heading"><span>LIVE CHAT</span><strong>Members only</strong></div><div className="chat-log">{(data?.messages || []).map((m: any) => <p key={m.id}><b>{m.username}</b> {m.body}</p>)}</div><form onSubmit={e => { e.preventDefault(); send('chat', { message }) }}><input value={message} onChange={e => setMessage(e.target.value)} placeholder="Say something…" maxLength={500} /><button>Send</button></form></article><article className="member-panel notes"><div className="panel-heading"><span>NOTES</span><strong>Saved to your account</strong></div><input value={note} onChange={e => setNote(e.target.value)} placeholder="Write a note…" /><button onClick={() => send('note', { title: 'Quick note', note })}>Save note</button><div className="saved-notes">{(data?.notes || []).map((n: any) => <p key={n.id}><b>{n.title}</b><br />{n.body}</p>)}</div></article><article className="member-panel tools"><div className="panel-heading"><span>TOOLS & APPS</span><strong>Open desk</strong></div><div className="tool-grid"><a href="/games/youtube/index.html">YouTube</a><a href="/tools">Calculator</a><a href="/tools">Timer</a><a href="/tools">Stopwatch</a><a href="/tools">Color lab</a><a href="/tools">Randomizer</a></div></article></section></main>
}
