'use client'
import { useEffect, useState } from 'react'
import { Ban, Check, LockKeyhole, ShieldCheck, Trash2, X } from 'lucide-react'
type Data = { bans: { id:string; identifier:string; reason:string|null }[]; requests:{id:string;title:string;icon:string|null;status:string}[]; games:{id:string;title:string;icon:string|null}[] }
export default function AdminPage(){const [password,setPassword]=useState('');const [unlocked,setUnlocked]=useState(false);const [data,setData]=useState<Data>({bans:[],requests:[],games:[]});const [identifier,setIdentifier]=useState('');const [reason,setReason]=useState('');const [error,setError]=useState('')
 async function load(){const r=await fetch('/api/admin');if(r.ok){setData(await r.json());setUnlocked(true)}} useEffect(()=>{void load()},[])
 async function login(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/admin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'login',password})});if(!r.ok){setError('Incorrect admin password.');return}setPassword('');await load()}
 async function action(body:object){await fetch('/api/admin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});await load()}
 async function remove(type:string,id:string){await fetch('/api/admin',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({type,id})});await load()}
 if(!unlocked)return <main className="admin-shell"><section className="admin-login"><div className="admin-lock"><LockKeyhole/></div><p className="eyebrow">GG-LOUNGE™ / CONTROL ROOM</p><h1>Admin access.</h1><p>Unlock the moderation and publishing console.</p><form onSubmit={login}><label htmlFor="admin-password">Admin password</label><input id="admin-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoFocus required/><button type="submit">Unlock console</button></form>{error&&<p className="admin-error">{error}</p>}</section></main>
 return <main className="admin-shell"><header className="admin-header"><div><p className="eyebrow"><ShieldCheck size={14}/> GG-LOUNGE™ / CONTROL ROOM</p><h1>Moderation console</h1></div><a href="/">Back to lounge</a></header><section className="admin-grid"><form className="admin-panel" onSubmit={e=>{e.preventDefault();void action({action:'ban',identifier,reason});setIdentifier('');setReason('')}}><div className="panel-heading"><Ban size={19}/><div><h2>Ban a visitor</h2><p>Block a username, email, or stable identifier.</p></div></div><label htmlFor="identifier">Identifier</label><input id="identifier" value={identifier} onChange={e=>setIdentifier(e.target.value)} required/><label htmlFor="reason">Reason</label><textarea id="reason" value={reason} onChange={e=>setReason(e.target.value)} rows={3}/><button type="submit">Add ban</button></form><section className="admin-panel"><div className="panel-heading"><ShieldCheck size={19}/><div><h2>Active bans</h2><p>{data.bans.length} records</p></div></div>{data.bans.map(b=><div className="ban-row" key={b.id}><div><strong>{b.identifier}</strong><span>{b.reason||'No reason provided'}</span></div><button onClick={()=>void remove('ban',b.id)} aria-label="Remove ban"><Trash2 size={16}/></button></div>)}</section></section><section className="admin-panel admin-wide"><div className="panel-heading"><Check size={19}/><div><h2>Game requests</h2><p>Approve or deny HTML uploads from the community.</p></div></div>{data.requests.length===0?<p className="muted">No pending requests.</p>:data.requests.map(r=><div className="request-row" key={r.id}><div><strong>{r.icon&&<img src={r.icon} alt=""/>}{r.title}</strong><span>{r.status}</span></div><div className="row-actions">{r.status==='pending'&&<><button onClick={()=>void action({action:'publish',id:r.id})}><Check size={15}/> Publish</button><button className="danger" onClick={()=>void action({action:'deny',id:r.id})}><X size={15}/> Deny</button></>}<button className="danger" onClick={()=>void remove('game',r.id)}><Trash2 size={15}/> Delete</button></div></div>)}</section><section className="admin-panel admin-wide"><div className="panel-heading"><Check size={19}/><div><h2>Published games</h2><p>Permanent games currently available in the lounge.</p></div></div>{data.games.map(g=><div className="request-row" key={g.id}><strong>{g.title}</strong><button className="danger" onClick={()=>void remove('game',g.id)}><Trash2 size={15}/> Delete</button></div>)}</section></main>}
