import {test} from 'node:test';import assert from 'node:assert/strict';
import {defaults,sanitizeSettings,normalizeDestination,iconHref,bindingFromEvent,matchesBinding,bindingLabel,accentInk,cursorValue} from '../lib/customization/settings';
test('settings defaults are independent and all new features opt in',()=>{const a=defaults(),b=defaults();a.theme.colors.accent='#000000';assert.notEqual(a.theme.colors.accent,b.theme.colors.accent);assert.equal(b.cloak.enabled,false);assert.equal(b.panic.enabled,false);assert.equal(b.reactive.enabled,false);});
test('settings reject CSS injection and clamp resource limits',()=>{const s=sanitizeSettings({theme:{colors:{accent:'url(javascript:alert(1))'}},background:{dim:999,blur:-4},cursor:{size:1000},reactive:{intensity:NaN}});assert.equal(s.theme.colors.accent,defaults().theme.colors.accent);assert.equal(s.background.dim,90);assert.equal(s.background.blur,0);assert.equal(s.cursor.size,64);assert.equal(s.reactive.intensity,50);});
test('malformed local storage cannot crash customization',()=>{for(const value of [null,[],42,'bad',{panic:null,theme:[],cursor:{image:'data:text/html,bad'}}])assert.equal(sanitizeSettings(value).version,1);});
test('panic accepts web destinations and a blank page, not executable URLs',()=>{assert.equal(normalizeDestination('example.com'), 'https://example.com/');assert.equal(normalizeDestination('/notes','https://lounge.test'),'https://lounge.test/notes');assert.equal(normalizeDestination('about:blank'),'about:blank');for(const value of ['javascript:alert(1)','data:text/html,bad','file:///secret','https://user:pass@example.com',''])assert.throws(()=>normalizeDestination(value));});
test('favicon supports URLs, emoji and safe uploaded raster data',()=>{assert.match(iconHref('📚'),/^data:image\/svg\+xml,/);assert.equal(iconHref('example.com/favicon.ico'),'https://example.com/favicon.ico');assert.equal(iconHref('/favicon.ico','https://lounge.test'),'https://lounge.test/favicon.ico');assert.equal(iconHref('data:image/png;base64,YQ=='),'data:image/png;base64,YQ==');for(const value of ['javascript:alert(1)','<svg onload=alert(1)>','data:text/html,bad','https://a:b@example.com/favicon.ico'])assert.throws(()=>iconHref(value));});
function event(code:string,extra:Record<string,unknown>={}){return {code,key:code.replace('Key','').toLowerCase(),ctrlKey:false,altKey:false,shiftKey:false,metaKey:false,repeat:false,isComposing:false,...extra} as unknown as KeyboardEvent;}
test('panic records regular keys and exact modifier combinations',()=>{const e=event('KeyS',{metaKey:true});const binding=bindingFromEvent(e);assert.equal(matchesBinding(e,binding),true);assert.equal(matchesBinding(event('KeyS'),binding),false);assert.equal(matchesBinding(event('KeyS',{metaKey:true,shiftKey:true}),binding),false);assert.match(bindingLabel(binding),/Meta.*S/);});
test('modifier-only, Escape and punctuation bindings are supported',()=>{for(const e of [event('ControlLeft',{ctrlKey:true}),event('ShiftLeft',{shiftKey:true}),event('Escape'),event('Backquote'),event('Space')])assert.equal(matchesBinding(e,bindingFromEvent(e)),true);});
test('repeat and IME composition never panic-loop',()=>{const b=bindingFromEvent(event('KeyP'));assert.equal(matchesBinding(event('KeyP',{repeat:true}),b),false);assert.equal(matchesBinding(event('KeyP',{isComposing:true}),b),false);});
test('button text contrast and cursor URL are derived safely',()=>{assert.equal(accentInk('#ffffff'),'#0b0d12');assert.equal(accentInk('#000000'),'#ffffff');assert.match(cursorValue({...defaults().cursor,preset:'ring'},'#ff0099'),/^url\("data:image\/svg\+xml,/);assert.equal(cursorValue(defaults().cursor,'#fff'),'');});
