const DB='ggl-personal-media';const STORE='assets';
export type PersonalMedia={id:string;name:string;kind:'image'|'video';blob:Blob;createdAt:number};
function open():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{if(!globalThis.indexedDB)return reject(new Error('This browser does not support local media storage.'));const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error('Local storage is unavailable.'));r.onblocked=()=>reject(new Error('Close other lounge tabs and retry the upload.'));});}
export async function saveMedia(file:File):Promise<PersonalMedia>{
  if(!file.size)throw new Error('That file is empty.');
  const image=/^image\/(png|jpeg|webp|gif|avif)$/.test(file.type),video=/^video\/(mp4|webm|ogg|quicktime)$/.test(file.type);
  if(!image&&!video)throw new Error('Choose a PNG/JPEG/WebP/GIF/AVIF image, or an MP4/WebM/OGG video.');
  if(file.size>(video?100:15)*1024*1024)throw new Error(video?'Videos must be 100 MB or smaller.':'Images must be 15 MB or smaller.');
  await validateMedia(file,video?'video':'image');
  const value:PersonalMedia={id:crypto.randomUUID(),name:file.name,kind:video?'video':'image',blob:file,createdAt:Date.now()};
  const db=await open();try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(value);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error||new Error('Your browser storage is full. Try a smaller file.'));tx.onabort=()=>reject(tx.error||new Error('Upload could not be saved locally.'));});return value;}finally{db.close();}
}
export async function getMedia(id:string):Promise<PersonalMedia|undefined>{const db=await open();try{return await new Promise((resolve,reject)=>{const r=db.transaction(STORE,'readonly').objectStore(STORE).get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}finally{db.close();}}
export async function deleteMedia(id:string):Promise<void>{if(!id)return;const db=await open();try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}finally{db.close();}}
function validateMedia(file:Blob,kind:'image'|'video'):Promise<void>{return new Promise((resolve,reject)=>{const src=URL.createObjectURL(file);const el=kind==='image'?new Image():document.createElement('video');let done=false;const finish=(error?:Error)=>{if(done)return;done=true;clearTimeout(timer);el.removeAttribute('src');if(el instanceof HTMLVideoElement)el.load();URL.revokeObjectURL(src);error?reject(error):resolve();};const timer=setTimeout(()=>finish(new Error('This file could not be decoded. Try PNG, JPEG, MP4 (H.264) or WebM.')),12000);el.onerror=()=>finish(new Error('This browser cannot decode that file. Try a different format.'));if(el instanceof HTMLVideoElement){el.preload='metadata';el.muted=true;el.onloadedmetadata=()=>el.videoWidth?finish():finish(new Error('Choose a video with a picture, not an audio-only file.'));}else el.onload=()=>finish();el.src=src;});}
export async function imageData(file:File,size:number):Promise<string>{
  if(!/^image\/(png|jpeg|webp|gif|avif|x-icon|vnd.microsoft.icon)$/.test(file.type)||file.size>4*1024*1024)throw new Error('Choose an image under 4 MB (PNG, JPEG, WebP, GIF, AVIF or ICO).');
  const src=URL.createObjectURL(file);try{const image=new Image();image.src=src;await image.decode();const canvas=document.createElement('canvas');canvas.width=canvas.height=size;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Image conversion is unavailable.');const scale=Math.min(size/image.width,size/image.height);const w=image.width*scale,h=image.height*scale;ctx.drawImage(image,(size-w)/2,(size-h)/2,w,h);return canvas.toDataURL('image/png');}catch{throw new Error('That image could not be read. Try PNG, JPEG or WebP.');}finally{URL.revokeObjectURL(src);}
}
