import { Analytics } from '@vercel/analytics/next'
import type { Metadata, Viewport } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'GG-Lounge — Small games. Big energy.',
  description: 'GG-LOUNGE™ is an independent browser arcade featuring ten handpicked games. A production of GG-LOUNGE STUDIOS™.',
  generator: 'GG-LOUNGE STUDIOS',
  manifest: '/manifest.webmanifest',
  applicationName: 'GG-Lounge',
  // Real brand files (public/brand, generated by scripts/gen-icons.py) rather
  // than the v0 defaults - /favicon.ico at the origin root also means every
  // static game tab gets the lounge mark for free.
  icons: {
    icon: [
      { url: '/brand/mark.svg', type: 'image/svg+xml' },
      { url: '/brand/icon-32.png', sizes: '32x32', type: 'image/png' },
      { url: '/brand/icon-192.png', sizes: '192x192', type: 'image/png' },
    ],
    apple: [{ url: '/brand/icon-180.png', sizes: '180x180', type: 'image/png' }],
    shortcut: '/brand/icon-32.png',
  },
  appleWebApp: {
    capable: true,
    title: 'Classroom Portal',
    statusBarStyle: 'black-translucent',
    startupImage: [],
  },
  other: {
    'msapplication-TileImage': '/brand/icon-128.png',
    'msapplication-TileColor': '#0d0f16',
    'mobile-web-app-capable': 'yes',
  },
}

export const viewport: Viewport = {
  colorScheme: 'dark',
  themeColor: '#101016',
  width: 'device-width',
  initialScale: 1,
  // phones: let the themed background run under the notch/home indicator and
  // keep pinch-zoom for tiny game HUDs
  viewportFit: 'cover',
  maximumScale: 5,
  userScalable: true,
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="bg-background">
      <head>
        {/*
          gg-boot.js is the lounge's client-side engine: tab cloaking, panic key,
          themes, reactive backgrounds and the video-engine prefs. It loads first so
          the cloak + theme are applied before the first paint (no flash of "GG
          Lounge" in the tab strip), and it also runs inside the game/video iframes.
        */}
        <script src="/gg/gg-boot.js" />
      </head>
      <body className="antialiased">
        {children}
        {process.env.NODE_ENV === 'production' && <Analytics />}
      </body>
    </html>
  )
}
