'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, Gamepad2, Heart, Maximize2, Play, Search, Sparkles, Trophy, X, Zap } from 'lucide-react'

type Game = { id: string; title: string; subtitle: string; description: string; genre: string; tone: string; mark: string; color: string; path: string; featured?: boolean }

const games: Game[] = [
  { id: 'cookie-clicker', title: 'Cookie Clicker', subtitle: 'Bake a bigger future.', description: 'Start with one tiny click and build an unstoppable cookie empire.', genre: 'Idle', tone: 'Cozy chaos', mark: 'CC', color: 'cookie', path: '/games/cookie-clicker/index.html', featured: true },
  { id: 'drive-mad', title: 'Drive Mad', subtitle: 'Keep it together.', description: 'Flip, fly, and find your line through a physics playground that hates straight roads.', genre: 'Racing', tone: 'Physics', mark: 'DM', color: 'drive', path: '/games/drive-mad/index.html' },
  { id: 'idle-mining', title: 'Idle Mining', subtitle: 'Dig deeper. Get richer.', description: 'Turn a quiet patch of earth into a sparkling underground operation.', genre: 'Idle', tone: 'Tycoon', mark: 'IM', color: 'mining', path: '/games/idle-mining/index.html' },
  { id: 'level-devil', title: 'Level Devil', subtitle: 'Trust nothing.', description: 'A platformer where every level has a trick, and every trick has teeth.', genre: 'Platformer', tone: 'Tricky', mark: 'LD', color: 'devil', path: '/games/level-devil/index.html' },
  { id: 'stack', title: 'Stack', subtitle: 'Build the perfect tower.', description: 'Drop each block with precision and chase a tower that never stops climbing.', genre: 'Arcade', tone: 'Precision', mark: 'ST', color: 'stack', path: '/games/stack/index.html' },
  { id: 'youtube', title: 'YouTube', subtitle: 'Browse. Watch. Repeat.', description: 'A self-contained video lounge with search, recommendations, and Watch Later.', genre: 'Video', tone: 'Explore', mark: 'YT', color: 'youtube', path: '/games/youtube/index.html' },
  { id: 'stickman-hook', title: 'Stickman Hook', subtitle: 'Swing into action.', description: 'Hook, swing, and launch through a kinetic obstacle course.', genre: 'Arcade', tone: 'Momentum', mark: 'SH', color: 'stack', path: '/games/stickman-hook/index.html' },
  { id: 'ragdoll-archers', title: 'Ragdoll Archers', subtitle: 'Aim. Fire. Bounce.', description: 'Take aim in a physics-packed archery arena full of ricochets.', genre: 'Arcade', tone: 'Physics', mark: 'RA', color: 'drive', path: '/games/ragdoll-archers/index.html' },
  { id: 'hextris', title: 'Hextris', subtitle: 'Spin. Match. Survive.', description: 'A hypnotic hexagonal puzzle where every move tightens the pressure.', genre: 'Puzzle', tone: 'Flow state', mark: 'HX', color: 'hextris', path: '/games/hextris/index.html' },
  { id: '2048', title: '2048', subtitle: 'Join the numbers.', description: 'Slide, merge, and think ahead in the classic number puzzle.', genre: 'Puzzle', tone: 'Strategy', mark: '20', color: 'twenty', path: '/games/2048/index.html' },
  { id: 'solar-smash', title: 'Solar Smash', subtitle: 'Break the impossible.', description: 'Unleash cosmic-scale destruction in a spectacular planetary sandbox.', genre: 'Simulation', tone: 'Cosmic', mark: 'SS', color: 'devil', path: '/games/solar-smash/index.html' },
  { id: 'drift-boss', title: 'Drift Boss', subtitle: 'One road. No brakes.', description: 'Hold the perfect line through an endless neon road and chase your best run.', genre: 'Racing', tone: 'Reflex', mark: 'DB', color: 'drive', path: '/games/drift-boss/index.html' },
  { id: 'moto-x3m', title: 'Moto X3M', subtitle: 'Ride the impossible.', description: 'Launch, flip, and land your way through explosive motorcycle stunt courses.', genre: 'Racing', tone: 'Stunts', mark: 'MX', color: 'drive', path: '/games/moto-x3m/index.html' },
  { id: 'subway-surfers', title: 'Subway Surfers', subtitle: 'Run without limits.', description: 'Dash through the city, dodge the tracks, and chase a higher score.', genre: 'Arcade', tone: 'Reflex', mark: 'SS', color: 'youtube', path: '/games/subway-surfers/index.html' },
  { id: 'survival-race', title: 'Survival Race', subtitle: 'Race the danger.', description: 'Keep your wheels steady and survive a relentless run of hazards.', genre: 'Racing', tone: 'Reflex', mark: 'SR', color: 'drive', path: '/games/survival-race/index.html' },
  { id: 'geometry-dash', title: 'Geometry Dash', subtitle: 'Jump the rhythm.', description: 'Sync your timing to the beat and clear a precision platforming gauntlet.', genre: 'Platformer', tone: 'Rhythm', mark: 'GD', color: 'hextris', path: '/games/geometry-dash/index.html' },
  { id: 'ovo', title: 'OvO', subtitle: 'Move with momentum.', description: 'Run, slide, and launch through a fast precision platformer.', genre: 'Platformer', tone: 'Precision', mark: 'OV', color: 'stack', path: '/games/ovo/index.html' },
  { id: 'eaglercraftx', title: 'EaglercraftX', subtitle: 'Build your world.', description: 'A block-building sandbox experience that runs directly in the browser.', genre: 'Adventure', tone: 'Sandbox', mark: 'EC', color: 'mining', path: '/games/eaglercraftx/index.html' },
  { id: 'vex-8', title: 'Vex 8', subtitle: 'Run the gauntlet.', description: 'Wall-jump, slide, and sprint through a sharp new platforming challenge.', genre: 'Platformer', tone: 'Precision', mark: 'V8', color: 'devil', path: '/games/vex-8/index.html' },
]
const filters = ['All games', 'Idle', 'Arcade', 'Puzzle', 'Racing', 'Platformer', 'Video', 'Favorites']

export default function Page() {
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All games'); const [favorites, setFavorites] = useState<string[]>([]); const [activeGame, setActiveGame] = useState<Game | null>(null); const [isLaunching, setIsLaunching] = useState(false); const [publishedGames, setPublishedGames] = useState<Game[]>([])
  useEffect(() => { fetch('/api/published-games').then((response) => response.ok ? response.json() : []).then((items: { id: string; title: string; icon: string | null }[]) => setPublishedGames(items.map((item) => ({ id: `published-${item.id}`, title: item.title, subtitle: 'Community release.', description: 'A community-submitted game approved by the GG-Lounge team.', genre: 'Community', tone: 'New release', mark: 'NEW', color: 'stack', path: `/games/${item.id}` })))).catch(() => undefined) }, [])
  useEffect(() => { if (!isLaunching) return; const timer = window.setTimeout(() => setIsLaunching(false), 2200); return () => window.clearTimeout(timer) }, [isLaunching])
  const allGames = useMemo(() => [...games, ...publishedGames], [publishedGames])
  const visibleGames = useMemo(() => allGames.filter((game) => `${game.title} ${game.genre} ${game.tone}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'All games' || game.genre === filter || (filter === 'Favorites' && favorites.includes(game.id)))), [favorites, filter, query])
  function launch(game: Game) { setActiveGame(game); setIsLaunching(true) }
  function toggleFavorite(id: string) { setFavorites((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]) }

  return <main className="lounge-shell">
    <style>{`.game-modal{height:min(92vh,900px);max-height:calc(100dvh - 24px)}.game-stage{position:relative;flex:1;min-height:0;height:calc(100% - 64px);overflow:hidden;background:#090a0e}.game-frame{position:relative;z-index:1;width:100%;height:100%;min-height:0;display:block}.launch-splash{position:absolute;inset:0;z-index:2;display:grid;place-content:center;justify-items:center;gap:18px;background:#090a0e;color:#f4f2ec;overflow:hidden;transition:opacity .8s cubic-bezier(.7,0,.2,1),visibility .8s}.launch-splash:before{content:'';position:absolute;inset:-20%;background:repeating-linear-gradient(0deg,transparent 0 7px,rgba(215,243,74,.06) 8px 9px);animation:scan 1.2s linear infinite}.launch-splash strong{position:relative;font-size:clamp(2.8rem,8vw,7rem);line-height:.8;letter-spacing:-.09em;text-align:center;text-shadow:4px 0 #ff6c83,-4px 0 #7d6bff;animation:glitch 1.1s steps(2) infinite}.launch-splash em{color:#d7f34a;font-style:normal}.launch-kicker,.launch-line{position:relative;color:#d7f34a;font-size:10px;font-weight:900;letter-spacing:.25em}.launch-line{width:140px;height:2px;background:#d7f34a;box-shadow:0 0 24px #d7f34a}.game-stage:not(.is-launching) .launch-splash{opacity:0;visibility:hidden;pointer-events:none}@keyframes scan{to{transform:translateY(20px)}}@keyframes glitch{0%,100%{transform:translate(0)}30%{transform:translate(2px,-1px)}32%{transform:translate(-3px,1px)}65%{transform:translate(1px,2px)}}`}</style>
    <div className="noise" aria-hidden="true" /><header className="site-header"><a href="#top" className="brand" aria-label="GG-Lounge home"><span className="brand-mark"><Gamepad2 size={19} /></span><span>GG-LOUNGE<span className="tm">™</span></span></a><nav className="header-nav" aria-label="Primary navigation"><a href="#games">Library</a><a href="/ai">AI Studio</a><a href="/tools">Tools & Apps</a><a href="/request-game">Request a game</a><a href="/member">Members</a><a href="/admin">Admin</a></nav><div className="header-status"><span className="live-dot" /> 19 titles / open all night</div></header>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><Sparkles size={14} /> THE INDEPENDENT ARCADE</p><h1>Stay a while.<br /><em>Play forever.</em></h1><p className="hero-text">A handpicked, no-filler collection of browser games for the minutes between everything.</p><a className="hero-link" href="#games">Enter the lounge <ArrowUpRight size={15} /></a><div className="hero-stats"><span><strong>19</strong> games</span><span><strong>∞</strong> replay value</span><span><strong>01</strong> lounge</span></div></div><div className="spotlight"><div className="spotlight-top"><span>SPOTLIGHT / 001</span><span className="spotlight-tag">FEATURED</span></div><div className="spotlight-art"><div className="orbit orbit-a" /><div className="orbit orbit-b" /><span className="spotlight-mark">CC</span><span className="spotlight-caption">SWEET<br />DESTRUCTION</span></div><div className="spotlight-bottom"><div><p className="card-kicker">IDLE · COZY CHAOS</p><h2>Cookie Clicker</h2><p>One click away from a very sweet problem.</p></div><button className="circle-play" onClick={() => launch(games[0])} aria-label="Play Cookie Clicker"><Play size={18} fill="currentColor" /></button></div></div></section>
    <section className="catalog" id="games"><div className="section-heading"><div><p className="eyebrow">THE ARCADE FLOOR</p><h2>Pick your poison<span>.</span></h2></div><div className="collection-note"><Trophy size={16} /><span><strong>{visibleGames.length.toString().padStart(2, '0')}</strong> available now</span></div></div><div className="toolbar"><div className="search-wrap"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search titles, genres, moods" aria-label="Search games" /></div><div className="filter-tabs" role="tablist" aria-label="Filter games">{filters.map((item) => <button key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)} role="tab" aria-selected={filter === item}>{item}</button>)}</div></div><div className="game-grid">{visibleGames.map((game, index) => <article className={`game-card ${game.color}`} key={game.id}><button className="favorite-button" onClick={() => toggleFavorite(game.id)} aria-label={`${favorites.includes(game.id) ? 'Remove' : 'Add'} ${game.title} ${favorites.includes(game.id) ? 'from' : 'to'} favorites`}><Heart size={17} fill={favorites.includes(game.id) ? 'currentColor' : 'none'} /></button><div className="game-art"><span className="game-mark">{game.mark}</span><small>{String(index + 1).padStart(2, '0')}</small></div><div className="game-info"><div><p className="card-kicker">{game.genre} · {game.tone}</p><h3>{game.title}</h3><p>{game.description}</p></div><button className="play-button" onClick={() => launch(game)}><Play size={13} fill="currentColor" /> Launch</button></div></article>)}</div>{visibleGames.length === 0 && <div className="empty-state"><Zap size={22} /><h3>No games found</h3><p>Try a different search or clear the filter.</p></div>}</section>
    <footer id="about"><div className="footer-top"><div className="footer-brand"><span className="brand-mark"><Gamepad2 size={17} /></span><strong>GG-LOUNGE<span className="tm">™</span></strong></div><span className="footer-rule" /><p>Made by <strong>Kai Chauhan</strong></p></div><div className="footer-bottom"><span>© 2026 GG-LOUNGE STUDIOS™. All rights reserved.</span><span>A Production of GG-LOUNGE STUDIOS™</span><span>Games remain property of their respective creators.</span></div></footer>
    {activeGame && <div className="game-modal" role="dialog" aria-modal="true" aria-label={`${activeGame.title} game`}><div className="modal-bar"><div><span className="modal-kicker">NOW PLAYING</span><strong>{activeGame.title}</strong></div><div className="modal-actions"><button onClick={() => document.querySelector<HTMLIFrameElement>('.game-frame')?.requestFullscreen()} aria-label="Fullscreen"><Maximize2 size={18} /></button><button onClick={() => setActiveGame(null)} aria-label="Close game"><X size={20} /></button></div></div><div className={`game-stage ${isLaunching ? 'is-launching' : ''}`}><div className="launch-splash" aria-hidden={!isLaunching}><span className="launch-kicker">GG-LOUNGE / ORIGINALS</span><strong>HOSTED ON<br /><em>GG-LOUNGE</em></strong><span className="launch-line" /></div><iframe className="game-frame" src={activeGame.path} title={activeGame.title} style={{ width: '100%', height: '100%', display: 'block', border: 0 }} /></div></div>}
  </main>
}
