export type Game = { id: string; title: string; subtitle: string; description: string; genre: string; tone: string; mark: string; color: string; path: string; icon?: string; featured?: boolean }
const ICON_DOMAIN_MAP: Record<string,string> = {
  "12-minibattles": "12minibattles.io",
  "1v1-lol": "1v1.lol",
  "2048": "play2048.co",
  "a-dance-of-fire-and-ice": "adofai.com",
  "a-small-world-cup": "asmallworldcup.io",
  "achievementunlocked": "armorgames.com",
  "agar-io": "agar.io",
  "alienhominid": "newgrounds.com",
  "among-us": "innersloth.com",
  "awesometanks2": "awesometanks2.io",
  "backrooms": "backrooms-game.io",
  "bad-ice-cream": "badicecream.io",
  "bad-ice-cream-3": "badicecream3.io",
  "bad-simulator": "badsimulator.io",
  "baldis-basics": "basicincomegame.com",
  "ball-blast": "ballblast.io",
  "baseball-bros": "baseballbros.io",
  "basket-bros": "basketbros.io",
  "basket-random": "basketrandom.io",
  "basketball-physics": "basketballphysics.io",
  "basketball-stars": "basketballstars.io",
  "big-tower-tiny-square": "bigtowertinysquare.io",
  "bitlife-simulator": "bitlifeonline.github.io",
  "bloxors": "bloxors.io",
  "bobtherobber2": "bobtherobber2.com",
  "boxing-random": "boxingrandom.io",
  "breakingthebank": "henrystickmin.com",
  "build-defend": "buildanddefend.io",
  "car-crash-test": "carcrashtest.io",
  "car-driving": "cardriving.io",
  "car-king-arena-2": "carking.io",
  "car-simulator": "carsimulator.io",
  "cb-clicker": "clickerheroes.com",
  "cell-machine": "samhogan.itch.io",
  "chrome-dino": "chromedino.io",
  "cluster-rush": "clusterrush.com",
  "color-puzzle": "colorpuzzle.io",
  "cookie-clicker": "orteil.dashnet.org",
  "core-ball": "coreball.io",
  "crazy-crash-landing": "crazycrashlanding.io",
  "crossyroad": "crossyroad.com",
  "cubefield": "cubefield.io",
  "cyber-cars": "cybercars.io",
  "dash-arena": "dasharena.io",
  "death-run-3d": "deathrun3d.io",
  "doodle-jump": "doodlejump.io",
  "draw-climber": "drawclimber.io",
  "drift-boss": "driftboss.io",
  "drift-hunters": "drift-hunters.com",
  "drift-race": "driftrace.io",
  "drive-mad": "drivemad.com",
  "drive-online": "driveonline.io",
  "ducklife1": "ducklife1.com",
  "ducklife2": "ducklife2.com",
  "ducklife3": "ducklife3.com",
  "dune-dash": "poki.com",
  "dune-surfer": "dunesurfer.io",
  "eaglercraftx": "eaglercraft.com",
  "edge-surf": "edgesurf.net",
  "elasticman": "elasticman.io",
  "escape-masters": "escapemasters.io",
  "escapingtheprison": "henrystickmin.com",
  "ev-io": "ev.io",
  "extreme-racing": "extremeracing.io",
  "fall-guys": "fallguys.com",
  "fancypantsadventures": "fancypantsadventure.com",
  "fireboywatergirlforesttemple": "fireboyandwatergirl.com",
  "first-aarc": "firstaarc.io",
  "flappy-bird": "flappybird.io",
  "fnaf": "scottgames.com",
  "fnaw": "gamejolt.com",
  "football-bros": "footballbros.io",
  "fruitninja": "halfbrick.com",
  "geometry-dash": "robtopgames.com",
  "geometry-rash": "geometrydash.io",
  "getaway-shootout": "getawayshootout.io",
  "gold-miner": "goldminer.io",
  "google-feud": "googlefeud.com",
  "granny": "granny-game.com",
  "grindcraft-remastered": "grindcraft.com",
  "gta-simulator": "gta-simulator.com",
  "gunspin": "gunspin.io",
  "hackertype": "hackertyper.com",
  "happy-glass": "happyglass.io",
  "happy-wheels": "totaljerkface.com",
  "helix-jump": "helixjump.io",
  "hextris": "hextris.io",
  "hole-io": "hole-io.com",
  "hop-fighters": "hopfighter.com",
  "house-of-hazards": "houseofhazards.io",
  "idle-mining": "idle-mining.com",
  "impossiblequiz": "theimpossiblequiz.io",
  "jelly-truck": "jellytruck.io",
  "jetpack-joyride": "jetpackjoyride.io",
  "knife-master": "knifemaster.io",
  "krunker": "krunker.io",
  "ks2-cs": "ks2-cs.io",
  "learntofly": "learntofly.io",
  "learntofly2": "learntofly2.io",
  "level-devil": "leveldevil.io",
  "mario": "nintendo.com",
  "minecraft-classic": "minecraft.net",
  "minecraft-skyblock": "minecraft.net",
  "minecraftbeta": "minecraft.net",
  "miner-dash": "minerdash.io",
  "monkey-mart": "monkey-mart.io",
  "monster-survival": "monstersurvival.io",
  "monster-truck": "monstertruck.io",
  "moto-x3m": "moto-x3m.net",
  "moto-x3m-winter": "moto-x3m.net",
  "mr-bullet": "mrbulllet.io",
  "n-gon": "n-gon.com",
  "ninja-parkour": "ninjaparkour.io",
  "noob-survival": "noobsurvival.io",
  "obby-shooter": "obbyshooter.io",
  "one-escape": "oneescape.io",
  "ovo": "ovo-game.com",
  "papasburgeria": "papasburgeria.com",
  "papaspizzaria": "papaspizzeria.io",
  "paper-io-2-3d": "paperio.site",
  "paper-minecraft": "paper-minecraft.com",
  "piano-tiles": "pianotiles.io",
  "pixel-shooter": "pixelshooter.io",
  "plants-vs-zombies": "ea.com",
  "poki": "paperio.site",
  "pumpkill-64": "itch.io",
  "qwop": "qwop.io",
  "ragdoll-archers": "ragdollarchers.com",
  "raven-shooting": "ravenshooting.io",
  "real-car-driving": "realcardriving.io",
  "red-ball-4": "redball4.com",
  "red-vs-blue": "redvsblue.io",
  "retro-bowl": "retrobowl.me",
  "riddleschool": "riddleschool.com",
  "riddleschool2": "riddleschool.com",
  "riddleschool3": "riddleschool.com",
  "rocket-goal-io": "rocketgoal.io",
  "rocket-league-2d": "rocketleague.com",
  "rooftop-run": "rooftoprun.io",
  "rooftop-snipers": "rooftopsnipers.io",
  "run-3": "run3.io",
  "run-rabbit-run": "runrabbitrun.io",
  "sandbox": "sandboxels.com",
  "shell-shockers": "shellshock.io",
  "short-life": "shortlife.io",
  "short-ride": "shortride.io",
  "sling-drift": "slingdrift.io",
  "slither-io": "slither.io",
  "slope": "slope-game.com",
  "slope-2": "slope2.io",
  "smashkarts": "smashkarts.io",
  "snow-rider-3d": "snowrider3d.io",
  "snowball-io": "snowball.io",
  "soccer-random": "soccerrandom.io",
  "solar-smash": "paradyne.com",
  "sonic-the-hedgehog": "sonic.com",
  "stack": "stackgame.io",
  "stack-bump-3d": "stackbump3d.io",
  "steal-brainrot": "stealabrainrot.io",
  "stealingthediamond": "henrystickmin.com",
  "steep-descent": "steepdescent.io",
  "stick-archers-battle": "stickarchers.io",
  "stick-war": "stickwar.io",
  "stickman-boost": "stickmanboost.io",
  "stickman-golf": "stickmangolf.io",
  "stickman-hook": "stickmanhook.com",
  "stumble-guys": "stumble-guys.io",
  "subway-surfers": "sybo.com",
  "survival-race": "poki.com",
  "swerve": "swerve.io",
  "swords-and-sandals": "swordsandsandals.io",
  "temple-run-2": "templerun2.com",
  "the-final-earth-2": "thefinalearth2.com",
  "the-little-giant": "thelittlegiant.io",
  "there-is-no-game": "thereisnogame.io",
  "they-are-coming": "theyarecoming.io",
  "thisistheonlylevel": "thisistheonlylevel.com",
  "tiny-fishing": "tinyfishing.io",
  "tower-defense": "towerdefense.io",
  "tunnel-rush": "tunnelrush.io",
  "twitch-tetris": "tetris.com",
  "uno": "uno-game.com",
  "vex-6": "vex6.io",
  "vex-8": "vex8.io",
  "vibes": "vibesgame.com",
  "volley-random": "volleyrandom.io",
  "vortex-tunnel": "vortextunnel.io",
  "war-the-knights": "wartheknights.io",
  "wheelie-bike": "wheeliebike.io",
  "wordle": "nytimes.com",
  "worlds-hardest-game": "worldshardestgame.io",
  "zombie-outbreak-arena": "zombiearena.io",
}
// Proper favicons: local icon if exists, else high-res Google favicon (128) via gstatic, fallback to DuckDuckGo
const LOCAL_ICON_MAP: Record<string,string> = {
  "a-dance-of-fire-and-ice": "/games/a-dance-of-fire-and-ice/splash.png",
  "achievementunlocked": "/games/achievementunlocked/achievementunlocked.png",
  "alienhominid": "/games/alienhominid/alienhominid.jpg",
  "among-us": "/games/among-us/red.png",
  "awesometanks2": "/games/awesometanks2/awesometanks2.jpg",
  "backrooms": "/games/backrooms/img/icon.png",
  "bad-ice-cream": "/games/bad-ice-cream/bad-ice-cream.png",
  "bad-ice-cream-2": "/games/bad-ice-cream-2/bad-ice-cream-2.png",
  "bad-ice-cream-3": "/games/bad-ice-cream-3/bad-ice-cream-3.png",
  "baldis-basics": "/games/baldis-basics/splash.png",
  "basket-random": "/games/basket-random/splash.jpeg",
  "basketball-stars": "/games/basketball-stars/assets/images/basketball-stars.png",
  "bloxors": "/games/bloxors/favicon.ico",
  "bobtherobber2": "/games/bobtherobber2/favicon.ico",
  "boxing-random": "/games/boxing-random/512x512.jpg",
  "breakingthebank": "/games/breakingthebank/breakingthebank.png",
  "cell-machine": "/games/cell-machine/TemplateData/favicon.ico",
  "chrome-dino": "/games/chrome-dino/favicon.ico",
  "cluster-rush": "/games/cluster-rush/icon.jpg",
  "cookie-clicker": "/games/cookie-clicker/img/favicon.ico",
  "core-ball": "/games/core-ball/pr_source.png",
  "crossyroad": "/games/crossyroad/crossyroad.png",
  "cubefield": "/games/cubefield/assets/splash.png",
  "death-run-3d": "/games/death-run-3d/TemplateData/favicon.ico",
  "doodle-jump": "/games/doodle-jump/doodle.png",
  "drift-boss": "/games/drift-boss/branding/logo.png",
  "drift-hunters": "/games/drift-hunters/drift-hunters.png",
  "drive-mad": "/games/drive-mad/drive-mad-logo-web.png",
  "ducklife1": "/games/ducklife1/ducklife.png",
  "ducklife2": "/games/ducklife2/ducklife2.png",
  "ducklife3": "/games/ducklife3/favicon.ico",
  "edge-surf": "/games/edge-surf/splash.png",
  "elasticman": "/games/elasticman/elasticman.jpg",
  "escapingtheprison": "/games/escapingtheprison/escapingtheprison.jpg",
  "fancypantsadventures": "/games/fancypantsadventures/fancypantsadventure.png",
  "fireboywatergirlforesttemple": "/games/fireboywatergirlforesttemple/icon-60x60.png",
  "flappy-bird": "/games/flappy-bird/assets/splash.png",
  "flashtetris": "/games/flashtetris/flashtetris.png",
  "fnaf": "/games/fnaf/favicon.ico",
  "fnaw": "/games/fnaw/favicon.ico",
  "fruitninja": "/games/fruitninja/FruitNinjaTeaser.jpg",
  "google-feud": "/games/google-feud/splash.png",
  "granny": "/games/granny/logo.png",
  "hackertype": "/games/hackertype/favicon.ico",
  "impossiblequiz": "/games/impossiblequiz/impossiblequiz.png",
  "jetpack-joyride": "/games/jetpack-joyride/splash.jpg",
  "knife-master": "/games/knife-master/512x512.jpg",
  "learntofly": "/games/learntofly/learntofly.png",
  "learntofly2": "/games/learntofly2/learn-to-fly-2.jpg",
  "level-devil": "/games/level-devil/favicon.png",
  "minecraft-classic": "/games/minecraft-classic/pack.png",
  "monkey-mart": "/games/monkey-mart/icons/icon-512.png",
  "moto-x3m": "/games/moto-x3m/favicon.ico",
  "n-gon": "/games/n-gon/favicon.ico",
  "ovo": "/games/ovo/icon-114.png",
  "papasburgeria": "/games/papasburgeria/ico.png",
  "papaspizzaria": "/games/papaspizzaria/papaspizzaria.jpg",
  "plants-vs-zombies": "/games/plants-vs-zombies/PVZ.ico",
  "poki": "/games/poki/images/icon512.png",
  "retro-bowl": "/games/retro-bowl/img/icon.jpg",
  "riddleschool": "/games/riddleschool/riddleschool.png",
  "riddleschool2": "/games/riddleschool2/riddleschool2.png",
  "riddleschool3": "/games/riddleschool3/riddleschool3.png",
  "rooftop-snipers": "/games/rooftop-snipers/img/thumb.png",
  "slope": "/games/slope/slope4.jpeg",
  "slope-2": "/games/slope-2/slope-2-logo.png",
  "slope-ball": "/games/slope-ball/icon.jpg",
  "snow-rider-3d": "/games/snow-rider-3d/favicon.ico",
  "stack-bump-3d": "/games/stack-bump-3d/thumbnail.jpg",
  "stealingthediamond": "/games/stealingthediamond/stealingthediamond.jpg",
  "stickman-boost": "/games/stickman-boost/icon-256.png",
  "stickman-golf": "/games/stickman-golf/splash.png",
  "temple-run-2": "/games/temple-run-2/ecb75761cc5768501b9345d4417c76f7.png",
  "thisistheonlylevel": "/games/thisistheonlylevel/thisistheonlylevel.png",
  "tiny-fishing": "/games/tiny-fishing/tiny-fishing.png",
  "tunnel-rush": "/games/tunnel-rush/style/webgl-logo.png",
  "twitch-tetris": "/games/twitch-tetris/logo.png",
  "wordle": "/games/wordle/img/logo_512x512.png",
  "worlds-hardest-game": "/games/worlds-hardest-game/images/splash.jpg",
  "youtube": "/games/youtube/icon.svg"
}

// Generic hosting domains that return host favicon, not game-specific — avoid showing wrong icon
const GENERIC_HOSTS = new Set([
  "github.io", "githubusercontent.com", "itch.io", "poki.com", "armorgames.com", "newgrounds.com",
  "henrystickmin.com", "crazygames.com", "y8.com", "gamedistribution.com", "coolmathgames.com",
  "google.com", "github.com"
])
const GENERIC_EXACT = new Set([
  "itch.io", "poki.com", "github.io" // exact host
])
function isGenericDomain(domain: string): boolean {
  if (!domain) return true
  // Check suffix
  for (const h of GENERIC_HOSTS) {
    if (domain === h || domain.endsWith("."+h)) return true
  }
  // Check reused domains (same favicon for multiple games) — handled below via dedup
  return false
}
// Build set of domains that appear multiple times (reused) — those are not unique game favicons
const DOMAIN_COUNTS: Record<string, number> = (() => {
  const c: Record<string, number> = {}
  for (const d of Object.values(ICON_DOMAIN_MAP)) c[d] = (c[d]||0)+1
  return c
})()

export function getGameIconUrl(id: string): string {
  // High-res generated covers in /game-icons/ — crisp, correct, not blurry favicons
  // All 192 games have a bespoke 512px cover; missing files fall back to premium typography cover via onError
  return `/game-icons/${id}.png`
}

export function getFaviconFallback(id: string): string {
  return `/game-icons/${id}.png`
}
export const games: Game[] = [
  { id: 'cookie-clicker', title: 'Cookie Clicker', subtitle: 'Bake a bigger future.', description: "Start with one tiny click and build an unstoppable cookie empire.", genre: 'Idle', tone: 'Cozy chaos', mark: 'CC', color: 'cookie', path: '/games/cookie-clicker/index.html', icon: getGameIconUrl('cookie-clicker'), featured: true },
  { id: 'drive-mad', title: 'Drive Mad', subtitle: 'Keep it together.', description: "Flip, fly, and find your line through a physics playground that hates straight roads.", genre: 'Racing', tone: 'Physics', mark: 'DM', color: 'drive', path: '/games/drive-mad/index.html', icon: getGameIconUrl('drive-mad'), featured: true },
  { id: 'idle-mining', title: 'Idle Mining', subtitle: 'Dig deeper. Get richer.', description: "Turn a quiet patch of earth into a sparkling underground operation.", genre: 'Idle', tone: 'Tycoon', mark: 'IM', color: 'mining', path: '/games/idle-mining/index.html', icon: getGameIconUrl('idle-mining') },
  { id: 'level-devil', title: 'Level Devil', subtitle: 'Trust nothing.', description: "A platformer where every level has a trick, and every trick has teeth.", genre: 'Platformer', tone: 'Tricky', mark: 'LD', color: 'devil', path: '/games/level-devil/index.html', icon: getGameIconUrl('level-devil') },
  { id: 'stack', title: 'Stack', subtitle: 'Build the perfect tower.', description: "Drop each block with precision and chase a tower that never stops climbing.", genre: 'Arcade', tone: 'Precision', mark: 'ST', color: 'stack', path: '/games/stack/index.html', icon: getGameIconUrl('stack'), featured: true },
  { id: 'stickman-hook', title: 'Stickman Hook', subtitle: 'Swing into action.', description: "Hook, swing, and launch through a kinetic obstacle course.", genre: 'Arcade', tone: 'Momentum', mark: 'SH', color: 'stack', path: '/games/stickman-hook/index.html', icon: getGameIconUrl('stickman-hook') },
  { id: 'ragdoll-archers', title: 'Ragdoll Archers', subtitle: 'Aim. Fire. Bounce.', description: "Take aim in a physics-packed archery arena full of ricochets.", genre: 'Arcade', tone: 'Physics', mark: 'RA', color: 'drive', path: '/games/ragdoll-archers/index.html', icon: getGameIconUrl('ragdoll-archers') },
  { id: 'hextris', title: 'Hextris', subtitle: 'Spin. Match. Survive.', description: "A hypnotic hexagonal puzzle where every move tightens the pressure.", genre: 'Puzzle', tone: 'Flow state', mark: 'HX', color: 'hextris', path: '/games/hextris/index.html', icon: getGameIconUrl('hextris') },
  { id: '2048', title: '2048', subtitle: 'Join the numbers.', description: "Slide, merge, and think ahead in the classic number puzzle.", genre: 'Puzzle', tone: 'Strategy', mark: '20', color: 'twenty', path: '/games/2048/index.html', icon: getGameIconUrl('2048') },
  { id: 'solar-smash', title: 'Solar Smash', subtitle: 'Break the impossible.', description: "Unleash cosmic-scale destruction in a spectacular planetary sandbox.", genre: 'Simulation', tone: 'Cosmic', mark: 'SS', color: 'devil', path: '/games/solar-smash/index.html', icon: getGameIconUrl('solar-smash') },
  { id: 'drift-boss', title: 'Drift Boss', subtitle: 'One road. No brakes.', description: "Hold the perfect line through an endless neon road and chase your best run.", genre: 'Racing', tone: 'Reflex', mark: 'DB', color: 'drive', path: '/games/drift-boss/index.html', icon: getGameIconUrl('drift-boss') },
  { id: 'moto-x3m', title: 'Moto X3M', subtitle: 'Ride the impossible.', description: "Launch, flip, and land your way through explosive motorcycle stunt courses.", genre: 'Racing', tone: 'Stunts', mark: 'MX', color: 'drive', path: '/games/moto-x3m/index.html', icon: getGameIconUrl('moto-x3m') },
  { id: 'subway-surfers', title: 'Subway Surfers', subtitle: 'Run without limits.', description: "Dash through the city, dodge the tracks, and chase a higher score.", genre: 'Arcade', tone: 'Reflex', mark: 'SS', color: 'youtube', path: '/games/subway-surfers/index.html', icon: getGameIconUrl('subway-surfers') },
  { id: 'survival-race', title: 'Survival Race', subtitle: 'Race the danger.', description: "Keep your wheels steady and survive a relentless run of hazards.", genre: 'Racing', tone: 'Reflex', mark: 'SR', color: 'drive', path: '/games/survival-race/index.html', icon: getGameIconUrl('survival-race') },
  { id: 'geometry-dash', title: 'Geometry Dash', subtitle: 'Jump the rhythm.', description: "Sync your timing to the beat and clear a precision platforming gauntlet.", genre: 'Platformer', tone: 'Rhythm', mark: 'GD', color: 'hextris', path: '/games/geometry-dash/index.html', icon: getGameIconUrl('geometry-dash') },
  { id: 'poki', title: 'Paper.io 2', subtitle: 'Claim it all.', description: "The real Paper.io 2 — loop out, capture territory, cut rival tails.", genre: 'Arcade', tone: 'Battle', mark: 'P2', color: 'youtube', path: '/games/poki/index.html', icon: getGameIconUrl('poki') },
  { id: 'vex-8', title: 'Vex 8', subtitle: 'Run the gauntlet.', description: "Wall-jump, slide, and sprint through a sharp new platforming challenge.", genre: 'Platformer', tone: 'Precision', mark: 'V8', color: 'devil', path: '/games/vex-8/index.html', icon: getGameIconUrl('vex-8') },
  { id: 'eaglercraftx', title: 'EaglercraftX', subtitle: 'Minecraft in a tab.', description: "The real EaglercraftX 1.8 client — singleplayer and multiplayer Minecraft, right in the browser.", genre: 'Sandbox', tone: 'Blocky', mark: 'EX', color: 'mining', path: '/games/eaglercraftx/index.html', icon: getGameIconUrl('eaglercraftx') },
  { id: 'backrooms', title: 'Backrooms', subtitle: 'You noclipped.', description: "The real Unity backrooms explorer — wander the humming halls of Level 0.", genre: 'Sandbox', tone: 'Horror', mark: 'BR', color: 'twenty', path: '/games/backrooms/index.html', icon: getGameIconUrl('backrooms') },
  { id: 'slope', title: 'Slope', subtitle: 'Roll at full speed.', description: "Steer a glowing ball down a deadly neon slope — how far can you ride?", genre: 'Arcade', tone: 'Reflex', mark: 'SL', color: 'hextris', path: '/games/slope/index.html', icon: getGameIconUrl('slope') },
  { id: 'retro-bowl', title: 'Retro Bowl', subtitle: 'Sunday, simplified.', description: "The beloved retro football sim — call plays, win bowls.", genre: 'Arcade', tone: 'Retro', mark: 'RB', color: 'drive', path: '/games/retro-bowl/index.html', icon: getGameIconUrl('retro-bowl') },
  { id: 'ovo', title: 'OvO', subtitle: 'Move like water.', description: "A slick parkour platformer — slide, dive and flow through precision levels.", genre: 'Platformer', tone: 'Precision', mark: 'OO', color: 'stack', path: '/games/ovo/index.html', icon: getGameIconUrl('ovo') },
  { id: 'temple-run-2', title: 'Temple Run 2', subtitle: 'Run for your life.', description: "The classic endless runner — escape the temple with the gold.", genre: 'Arcade', tone: 'Reflex', mark: 'TR', color: 'cookie', path: '/games/temple-run-2/index.html', icon: getGameIconUrl('temple-run-2') },
  { id: 'tunnel-rush', title: 'Tunnel Rush', subtitle: 'Dodge at light speed.', description: "Blast through a spinning 3D tunnel of obstacles.", genre: 'Arcade', tone: 'Reflex', mark: 'TU', color: 'devil', path: '/games/tunnel-rush/index.html', icon: getGameIconUrl('tunnel-rush') },
  { id: 'doodle-jump', title: 'Doodle Jump', subtitle: 'Bounce forever.', description: "Hop up an endless page of platforms in the one-thumb classic.", genre: 'Arcade', tone: 'Retro', mark: 'DJ', color: 'mining', path: '/games/doodle-jump/index.html', icon: getGameIconUrl('doodle-jump') },
  { id: 'cluster-rush', title: 'Cluster Rush', subtitle: 'Jump truck to truck.', description: "First-person parkour across speeding trucks — don’t fall.", genre: 'Platformer', tone: 'Precision', mark: 'CR', color: 'drive', path: '/games/cluster-rush/index.html', icon: getGameIconUrl('cluster-rush') },
  { id: 'jetpack-joyride', title: 'Jetpack Joyride', subtitle: 'Fly. Dodge. Profit.', description: "Blast through the lab with a machine-gun jetpack.", genre: 'Arcade', tone: 'Reflex', mark: 'JJ', color: 'youtube', path: '/games/jetpack-joyride/index.html', icon: getGameIconUrl('jetpack-joyride') },
  { id: 'drift-hunters', title: 'Drift Hunters', subtitle: 'Slide everything.', description: "Tune your ride and chain drifts across huge 3D tracks.", genre: 'Racing', tone: 'Drift', mark: 'DH', color: 'drive', path: '/games/drift-hunters/index.html', icon: getGameIconUrl('drift-hunters') },
  { id: 'rooftop-snipers', title: 'Rooftop Snipers', subtitle: 'Two idiots. One roof.', description: "Knock your opponent off the roof in this chaotic 2-player duel.", genre: 'Arcade', tone: 'Chaos', mark: 'RS', color: 'cookie', path: '/games/rooftop-snipers/index.html', icon: getGameIconUrl('rooftop-snipers') },
  { id: 'worlds-hardest-game', title: 'World’s Hardest Game', subtitle: 'It means it.', description: "Dodge the blue dots and beat the most rage-inducing maze ever.", genre: 'Puzzle', tone: 'Rage', mark: 'WH', color: 'devil', path: '/games/worlds-hardest-game/index.html', icon: getGameIconUrl('worlds-hardest-game') },
  { id: 'fireboywatergirlforesttemple', title: 'Fireboy & Watergirl', subtitle: 'Two players, one temple.', description: "Solve puzzles together in the Forest Temple — the co-op classic.", genre: 'Puzzle', tone: 'Co-op', mark: 'FW', color: 'stack', path: '/games/fireboywatergirlforesttemple/index.html', icon: getGameIconUrl('fireboywatergirlforesttemple') },
  { id: 'impossiblequiz', title: 'The Impossible Quiz', subtitle: 'Think outside the box.', description: "Trick questions, bombs and pure chaos — answer carefully.", genre: 'Puzzle', tone: 'Chaos', mark: 'IQ', color: 'twenty', path: '/games/impossiblequiz/index.html', icon: getGameIconUrl('impossiblequiz') },
  { id: 'ducklife2', title: 'Duck Life 2', subtitle: 'Train your duck.', description: "Race, swim and fly your duck to championship glory.", genre: 'Simulation', tone: 'Cute', mark: 'DL', color: 'mining', path: '/games/ducklife2/index.html', icon: getGameIconUrl('ducklife2') },
  { id: 'escapingtheprison', title: 'Escaping the Prison', subtitle: 'Choose wisely.', description: "The Henry Stickmin classic — pick your escape route.", genre: 'Puzzle', tone: 'Story', mark: 'EP', color: 'stack', path: '/games/escapingtheprison/index.html', icon: getGameIconUrl('escapingtheprison') },
  { id: 'stealingthediamond', title: 'Stealing the Diamond', subtitle: 'Go big.', description: "Henry Stickmin returns — steal the Tunisian Diamond your way.", genre: 'Puzzle', tone: 'Story', mark: 'SD', color: 'twenty', path: '/games/stealingthediamond/index.html', icon: getGameIconUrl('stealingthediamond') },
  { id: 'fancypantsadventures', title: 'Fancy Pants', subtitle: 'Run fancy.', description: "The legendary stick-figure platformer with the smoothest moves.", genre: 'Platformer', tone: 'Retro', mark: 'FP', color: 'youtube', path: '/games/fancypantsadventures/index.html', icon: getGameIconUrl('fancypantsadventures') },
  { id: 'papaspizzaria', title: 'Papa’s Pizzeria', subtitle: 'Top. Bake. Serve.', description: "Run the pizzeria — take orders, bake pizzas, keep customers happy.", genre: 'Simulation', tone: 'Cute', mark: 'PP', color: 'cookie', path: '/games/papaspizzaria/index.html', icon: getGameIconUrl('papaspizzaria') },
  { id: 'papasburgeria', title: 'Papa’s Burgeria', subtitle: 'Flip and stack.', description: "Grill, stack and serve the perfect burgers.", genre: 'Simulation', tone: 'Cute', mark: 'PB', color: 'cookie', path: '/games/papasburgeria/index.html', icon: getGameIconUrl('papasburgeria') },
  { id: 'riddleschool', title: 'Riddle School', subtitle: 'Escape class.', description: "Point, click and puzzle your way out of school.", genre: 'Puzzle', tone: 'Story', mark: 'RD', color: 'stack', path: '/games/riddleschool/index.html', icon: getGameIconUrl('riddleschool') },
  { id: 'bloxors', title: 'Bloxors', subtitle: 'Roll the block.', description: "Tip the block onto the goal without falling off the edge.", genre: 'Puzzle', tone: 'Strategy', mark: 'BX', color: 'stack', path: '/games/bloxors/index.html', icon: getGameIconUrl('bloxors') },
  { id: 'basket-random', title: 'Basket Random', subtitle: 'Chaos basketball.', description: "Floppy 2-player hoops — first to 5 wins.", genre: 'Arcade', tone: 'Chaos', mark: 'BK', color: 'drive', path: '/games/basket-random/index.html', icon: getGameIconUrl('basket-random') },
  { id: 'boxing-random', title: 'Boxing Random', subtitle: 'Floppy fists.', description: "Wobbly 2-player boxing — knock them out.", genre: 'Arcade', tone: 'Chaos', mark: 'BO', color: 'devil', path: '/games/boxing-random/index.html', icon: getGameIconUrl('boxing-random') },
  { id: 'alienhominid', title: 'Alien Hominid', subtitle: 'Run-and-gun classic.', description: "Blast through the FBI as the little yellow alien.", genre: 'Arcade', tone: 'Retro', mark: 'AH', color: 'mining', path: '/games/alienhominid/index.html', icon: getGameIconUrl('alienhominid') },
  { id: 'awesometanks2', title: 'Awesome Tanks 2', subtitle: 'Upgrade and destroy.', description: "Blast through enemy tanks and upgrade your ride.", genre: 'Arcade', tone: 'Battle', mark: 'AT', color: 'drive', path: '/games/awesometanks2/index.html', icon: getGameIconUrl('awesometanks2') },
  { id: 'baldis-basics', title: 'Baldi’s Basics', subtitle: 'Math. Horror. Run.', description: "Collect notebooks and escape Baldi in the cult horror hit.", genre: 'Arcade', tone: 'Horror', mark: 'BB', color: 'twenty', path: '/games/baldis-basics/index.html', icon: getGameIconUrl('baldis-basics') },
  { id: 'bad-ice-cream', title: 'Bad Ice Cream', subtitle: 'Chill out.', description: "Maze-munching arcade fun — grab fruit, dodge enemies.", genre: 'Arcade', tone: 'Retro', mark: 'BI', color: 'hextris', path: '/games/bad-ice-cream/index.html', icon: getGameIconUrl('bad-ice-cream') },
  { id: 'crossyroad', title: 'Crossy Road', subtitle: 'Why did it cross?', description: "Hop across roads and rivers — don’t get flattened.", genre: 'Arcade', tone: 'Reflex', mark: 'XO', color: 'mining', path: '/games/crossyroad/index.html', icon: getGameIconUrl('crossyroad') },
  { id: 'cubefield', title: 'Cubefield', subtitle: 'Dodge the cubes.', description: "Fly through an endless field of cubes at breakneck speed.", genre: 'Arcade', tone: 'Reflex', mark: 'CB', color: 'stack', path: '/games/cubefield/index.html', icon: getGameIconUrl('cubefield') },
  { id: 'edge-surf', title: 'Edge Surf', subtitle: 'Ride the waves.', description: "The endless surfer — dodge obstacles and grab coins.", genre: 'Arcade', tone: 'Reflex', mark: 'ES', color: 'hextris', path: '/games/edge-surf/index.html', icon: getGameIconUrl('edge-surf') },
  { id: 'flappy-bird', title: 'Flappy Bird', subtitle: 'Just one more tap.', description: "The original rage-tap classic — thread the pipes.", genre: 'Arcade', tone: 'Reflex', mark: 'FB', color: 'youtube', path: '/games/flappy-bird/index.html', icon: getGameIconUrl('flappy-bird') },
  { id: 'fruitninja', title: 'Fruit Ninja', subtitle: 'Slice everything.', description: "Swipe-slice fruit combos and dodge the bombs.", genre: 'Arcade', tone: 'Reflex', mark: 'FN', color: 'devil', path: '/games/fruitninja/index.html', icon: getGameIconUrl('fruitninja') },
  { id: 'getaway-shootout', title: 'Getaway Shootout', subtitle: 'Race to escape.', description: "Chaotic 2-player showdowns — grab the getaway first.", genre: 'Arcade', tone: 'Chaos', mark: 'GS', color: 'twenty', path: '/games/getaway-shootout/index.html', icon: getGameIconUrl('getaway-shootout') },
  { id: 'google-feud', title: 'Google Feud', subtitle: 'Guess the autocomplete.', description: "Quiz party game — guess how the internet finishes the sentence.", genre: 'Puzzle', tone: 'Party', mark: 'GF', color: 'stack', path: '/games/google-feud/index.html', icon: getGameIconUrl('google-feud') },
  { id: 'hackertype', title: 'Hacker Type', subtitle: 'Look like a hacker.', description: "Mash keys, hack the mainframe, look awesome.", genre: 'Arcade', tone: 'Fun', mark: 'HT', color: 'mining', path: '/games/hackertype/index.html', icon: getGameIconUrl('hackertype') },
  { id: 'knife-master', title: 'Knife Master', subtitle: 'Hit the target.', description: "Time your throws and stick every knife.", genre: 'Arcade', tone: 'Reflex', mark: 'KM', color: 'devil', path: '/games/knife-master/index.html', icon: getGameIconUrl('knife-master') },
  { id: 'thisistheonlylevel', title: 'This Is The Only Level', subtitle: 'One level. Many lies.', description: "Same stage, new twist every time — think fast.", genre: 'Platformer', tone: 'Puzzle', mark: 'TO', color: 'stack', path: '/games/thisistheonlylevel/index.html', icon: getGameIconUrl('thisistheonlylevel') },
  { id: 'tiny-fishing', title: 'Tiny Fishing', subtitle: 'Cast and relax.', description: "Hook fish, upgrade your rod, dive deeper.", genre: 'Idle', tone: 'Chill', mark: 'TF', color: 'hextris', path: '/games/tiny-fishing/index.html', icon: getGameIconUrl('tiny-fishing') },
  { id: 'wordle', title: 'Wordle', subtitle: 'Six tries.', description: "Guess the 5-letter word in six tries — the daily classic.", genre: 'Puzzle', tone: 'Strategy', mark: 'WO', color: 'mining', path: '/games/wordle/index.html', icon: getGameIconUrl('wordle') },
  { id: 'fnaw', title: 'FNaW', subtitle: 'Nights at Winston’s.', description: "A Five Nights fan game — survive the night shift as the janitor.", genre: 'Arcade', tone: 'Horror', mark: 'NW', color: 'twenty', path: '/games/fnaw/index.html', icon: getGameIconUrl('fnaw') },
  { id: 'stack-bump-3d', title: 'Stack Bump 3D', subtitle: 'Smash the stack.', description: "Bounce through spinning helix stacks.", genre: 'Arcade', tone: 'Reflex', mark: 'SB', color: 'twenty', path: '/games/stack-bump-3d/index.html', icon: getGameIconUrl('stack-bump-3d') },
  { id: 'death-run-3d', title: 'Death Run 3D', subtitle: 'Outrun death.', description: "Sprint through a neon tunnel of moving walls.", genre: 'Arcade', tone: 'Reflex', mark: 'DR', color: 'devil', path: '/games/death-run-3d/index.html', icon: getGameIconUrl('death-run-3d') },
  { id: 'a-dance-of-fire-and-ice', title: 'A Dance of Fire and Ice', subtitle: 'One-button rhythm.', description: "Guide two orbiting planets down a strict rhythm path.", genre: 'Platformer', tone: 'Rhythm', mark: 'DF', color: 'youtube', path: '/games/a-dance-of-fire-and-ice/index.html', icon: getGameIconUrl('a-dance-of-fire-and-ice') },
  { id: 'n-gon', title: 'n-gon', subtitle: 'Physics playground.', description: "A deep physics sandbox shooter — bend gravity, build, destroy.", genre: 'Sandbox', tone: 'Chaos', mark: 'NG', color: 'stack', path: '/games/n-gon/index.html', icon: getGameIconUrl('n-gon') },
  { id: 'achievementunlocked', title: 'Achievement Unlocked', subtitle: 'Unlock everything.', description: "The meta game about unlocking achievements — including this one.", genre: 'Platformer', tone: 'Meta', mark: 'AU', color: 'twenty', path: '/games/achievementunlocked/index.html', icon: getGameIconUrl('achievementunlocked') },
  { id: 'cell-machine', title: 'Cell Machine', subtitle: 'Program cells.', description: "Build self-replicating machines from logic cells.", genre: 'Puzzle', tone: 'Strategy', mark: 'CM', color: 'mining', path: '/games/cell-machine/index.html', icon: getGameIconUrl('cell-machine') },
  { id: 'mario', title: 'Mario', subtitle: 'Wahoo.', description: "The classic platforming adventure — stomp, jump, save the day.", genre: 'Platformer', tone: 'Retro', mark: 'M!', color: 'devil', path: '/games/mario/index.html', icon: getGameIconUrl('mario') },
  { id: 'bobtherobber2', title: 'Bob the Robber 2', subtitle: 'Steal quietly.', description: "Sneak past guards and grab the loot.", genre: 'Puzzle', tone: 'Stealth', mark: 'B2', color: 'stack', path: '/games/bobtherobber2/index.html', icon: getGameIconUrl('bobtherobber2') },
  { id: 'learntofly', title: 'Learn to Fly', subtitle: 'Penguins can fly.', description: "Launch the penguin, upgrade, fly farther.", genre: 'Arcade', tone: 'Retro', mark: 'LF', color: 'hextris', path: '/games/learntofly/index.html', icon: getGameIconUrl('learntofly') },
  { id: 'learntofly2', title: 'Learn to Fly 2', subtitle: 'Fly farther.', description: "Bigger launches, better gear, dumber penguin.", genre: 'Arcade', tone: 'Retro', mark: 'L2', color: 'youtube', path: '/games/learntofly2/index.html', icon: getGameIconUrl('learntofly2') },
  { id: 'breakingthebank', title: 'Breaking the Bank', subtitle: 'Get rich quick.', description: "Henry Stickmin’s first heist — pick your tool.", genre: 'Puzzle', tone: 'Story', mark: 'BT', color: 'stack', path: '/games/breakingthebank/index.html', icon: getGameIconUrl('breakingthebank') },
  { id: 'among-us', title: 'Among Us', subtitle: 'Find the impostor.', description: "The social deduction hit — finish tasks, eject the impostor.", genre: 'Arcade', tone: 'Party', mark: 'AM', color: 'devil', path: '/games/among-us/index.html', icon: getGameIconUrl('among-us') },
  { id: 'elasticman', title: 'Elastic Man', subtitle: 'Stretch his face.', description: "The viral silly toy — pull, stretch and giggle.", genre: 'Arcade', tone: 'Fun', mark: 'EM', color: 'cookie', path: '/games/elasticman/index.html', icon: getGameIconUrl('elasticman') },
  { id: 'chrome-dino', title: 'Chrome Dino', subtitle: 'No internet? No problem.', description: "The offline runner — jump cacti, dodge pterodactyls.", genre: 'Arcade', tone: 'Retro', mark: 'CD', color: 'stack', path: '/games/chrome-dino/index.html', icon: getGameIconUrl('chrome-dino') },
  { id: 'core-ball', title: 'Core Ball', subtitle: 'Thread the core.', description: "Time your shots into the spinning core — don’t touch.", genre: 'Arcade', tone: 'Reflex', mark: 'CO', color: 'hextris', path: '/games/core-ball/index.html', icon: getGameIconUrl('core-ball') },
  { id: 'monkey-mart', title: 'Monkey Mart', subtitle: 'Monkey business.', description: "Run a grocery store with monkey staff — stock shelves, serve customers.", genre: 'Simulation', tone: 'Cute', mark: 'MM', color: 'mining', path: '/games/monkey-mart/index.html', icon: getGameIconUrl('monkey-mart') },
  { id: 'minecraft-classic', title: 'Minecraft Classic', subtitle: 'The original, in a tab.', description: "Mojang’s official Classic build — place and break blocks with friends.", genre: 'Sandbox', tone: 'Blocky', mark: 'MC', color: 'mining', path: '/games/minecraft-classic/index.html', icon: getGameIconUrl('minecraft-classic') },
  { id: 'minecraftbeta', title: 'Minecraft Beta', subtitle: 'Survive the night.', description: "A playable beta-style Minecraft — mine, build, survive.", genre: 'Sandbox', tone: 'Blocky', mark: 'MB', color: 'mining', path: '/games/minecraftbeta/index.html', icon: getGameIconUrl('minecraftbeta') },
  { id: 'riddleschool2', title: 'Riddle School 2', subtitle: 'Escape again.', description: "Point, click and puzzle your way out — the sequel.", genre: 'Puzzle', tone: 'Story', mark: 'R2', color: 'stack', path: '/games/riddleschool2/index.html', icon: getGameIconUrl('riddleschool2') },
  { id: 'riddleschool3', title: 'Riddle School 3', subtitle: 'No skipping class.', description: "The third escape — trickier puzzles, funnier endings.", genre: 'Puzzle', tone: 'Story', mark: 'R3', color: 'stack', path: '/games/riddleschool3/index.html', icon: getGameIconUrl('riddleschool3') },
  { id: 'bad-ice-cream-3', title: 'Bad Ice Cream 3', subtitle: 'Triple chill.', description: "The iciest one yet — 40 levels of fruity mayhem.", genre: 'Arcade', tone: 'Retro', mark: 'I3', color: 'hextris', path: '/games/bad-ice-cream-3/index.html', icon: getGameIconUrl('bad-ice-cream-3') },
  { id: 'slope-2', title: 'Slope 2', subtitle: 'Faster. Steeper.', description: "The sequel to the endless neon slope — even less mercy.", genre: 'Arcade', tone: 'Reflex', mark: 'S2', color: 'hextris', path: '/games/slope-2/index.html', icon: getGameIconUrl('slope-2') },
  { id: 'twitch-tetris', title: 'Tetris', subtitle: 'Pure blocks.', description: "A clean modern Tetris — spin, drop, clear.", genre: 'Puzzle', tone: 'Retro', mark: 'TE', color: 'twenty', path: '/games/twitch-tetris/index.html', icon: getGameIconUrl('twitch-tetris') },
  { id: 'ducklife1', title: 'Duck Life', subtitle: 'Train your duck.', description: "The original — run, swim and fly to racing glory.", genre: 'Simulation', tone: 'Cute', mark: 'D1', color: 'mining', path: '/games/ducklife1/index.html', icon: getGameIconUrl('ducklife1') },
  { id: 'ducklife3', title: 'Duck Life 3', subtitle: 'Evolve your duck.', description: "Bigger races, tougher training, champion ducks.", genre: 'Simulation', tone: 'Cute', mark: 'D3', color: 'mining', path: '/games/ducklife3/index.html', icon: getGameIconUrl('ducklife3') },
  { id: 'basketball-stars', title: 'Basketball Stars', subtitle: 'Ball is life.', description: "Fast 1v1 hoops — shoot, steal and dunk on your rival.", genre: 'Arcade', tone: 'Chaos', mark: 'BS', color: 'drive', path: '/games/basketball-stars/index.html', icon: getGameIconUrl('basketball-stars') },
  { id: 'stickman-golf', title: 'Stickman Golf', subtitle: 'Fore!', description: "Fling the stickman through crazy golf courses.", genre: 'Arcade', tone: 'Fun', mark: 'SG', color: 'mining', path: '/games/stickman-golf/index.html', icon: getGameIconUrl('stickman-golf') },
  { id: 'stickman-boost', title: 'Stickman Boost', subtitle: 'Hold on tight.', description: "High-speed stickman runner — jump, slide, survive.", genre: 'Arcade', tone: 'Reflex', mark: 'ST', color: 'stack', path: '/games/stickman-boost/index.html', icon: getGameIconUrl('stickman-boost') },
  { id: 'fnaf', title: 'Five Nights at Freddy’s', subtitle: 'Survive five nights.', description: "The original FNAF — watch the cameras, save power, keep them out.", genre: 'Arcade', tone: 'Horror', mark: 'F1', color: 'twenty', path: '/games/fnaf/index.html', icon: getGameIconUrl('fnaf') },
  { id: 'happy-wheels', title: 'Happy Wheels', subtitle: 'Brutal ragdoll racing.', description: "The legendary obstacle racer — finish in one piece. Probably not.", genre: 'Platformer', tone: 'Chaos', mark: 'HW', color: 'devil', path: '/games/happy-wheels/index.html', icon: getGameIconUrl('happy-wheels') },
  { id: 'run-3', title: 'Run 3', subtitle: 'Don’t fall off.', description: "Run, skate and float through the tunnels of space.", genre: 'Platformer', tone: 'Reflex', mark: 'RN', color: 'stack', path: '/games/run-3/index.html', icon: getGameIconUrl('run-3') },
  { id: 'red-ball-4', title: 'Red Ball 4', subtitle: 'Roll to the rescue.', description: "All three volumes — bounce, squash and outsmart the squares.", genre: 'Platformer', tone: 'Retro', mark: 'R4', color: 'devil', path: '/games/red-ball-4/index.html', icon: getGameIconUrl('red-ball-4') },
  { id: 'plants-vs-zombies', title: 'Plants vs Zombies', subtitle: 'Hold the lawn.', description: "The classic lawn defense — pea-shooters vs the horde.", genre: 'Arcade', tone: 'Strategy', mark: 'PV', color: 'mining', path: '/games/plants-vs-zombies/index.html', icon: getGameIconUrl('plants-vs-zombies') },
  { id: 'snow-rider-3d', title: 'Snow Rider 3D', subtitle: 'Shred the mountain.', description: "Dodge trees and grab gifts on an endless snowy ride.", genre: 'Arcade', tone: 'Reflex', mark: 'SN', color: 'hextris', path: '/games/snow-rider-3d/index.html', icon: getGameIconUrl('snow-rider-3d') },
  { id: 'granny', title: 'Granny', subtitle: 'Don’t make a sound.', description: "Escape Granny’s house in 5 days — quietly.", genre: 'Arcade', tone: 'Horror', mark: 'GR', color: 'twenty', path: '/games/granny/index.html', icon: getGameIconUrl('granny') },
  { id: 'hole-io', title: 'Hole.io', subtitle: 'Eat the city.', description: "Local unblocked hole-eater — swallow buildings, grow huge, own the map. Play instantly — no downloads.", genre: 'Arcade', tone: 'Battle', mark: 'HO', color: 'mining', path: '/games/hole-io/index.html', icon: getGameIconUrl('hole-io'), featured: true },
  { id: '1v1-lol', title: '1v1.LOL', subtitle: 'Build. Aim. Eliminate.', description: "Fast multiplayer — build, shoot and win.", genre: 'Arcade', tone: 'Battle', mark: '1V', color: 'devil', path: '/games/1v1-lol/index.html', icon: getGameIconUrl('1v1-lol') },
  { id: 'krunker', title: 'Krunker', subtitle: 'FPS in a tab.', description: "Fast FPS multiplayer — join and play.", genre: 'Arcade', tone: 'Battle', mark: 'KR', color: 'stack', path: '/games/krunker/index.html', icon: getGameIconUrl('krunker') },
  { id: 'smashkarts', title: 'SmashKarts', subtitle: 'Drive. Smash. Win.', description: "SmashKarts.io — kart chaos with weapons, full multiplayer.", genre: 'Racing', tone: 'Battle', mark: 'SK', color: 'drive', path: '/games/smashkarts/index.html', icon: getGameIconUrl('smashkarts') },
  { id: 'ev-io', title: 'Ev.io', subtitle: 'Sci-fi shooter.', description: "Sci-fi FPS — all maps, ranked.", genre: 'Arcade', tone: 'Battle', mark: 'EV', color: 'hextris', path: '/games/ev-io/index.html', icon: getGameIconUrl('ev-io') },
  { id: 'shell-shockers', title: 'Shell Shockers', subtitle: 'Egg warfare.', description: "Shell Shockers — egg FPS, all eggs & weapons, via lounge.", genre: 'Arcade', tone: 'Battle', mark: 'SS', color: 'cookie', path: '/games/shell-shockers/index.html', icon: getGameIconUrl('shell-shockers') },
  { id: 'agar-io', title: 'Agar.io', subtitle: 'Eat or be eaten.', description: "Agar.io — eat cells, split, full multiplayer unblocked.", genre: 'Arcade', tone: 'Battle', mark: 'AG', color: 'hextris', path: '/games/agar-io/index.html', icon: getGameIconUrl('agar-io') },
  { id: 'slither-io', title: 'Slither.io', subtitle: 'Slither big.', description: "Slither.io — grow the snake, trap others, full online.", genre: 'Arcade', tone: 'Battle', mark: 'SL', color: 'mining', path: '/games/slither-io/index.html', icon: getGameIconUrl('slither-io') },
  { id: 'paper-io-2-3d', title: 'Paper.io 3D', subtitle: 'Paint the map.', description: "Capture territory — cut tails, paint the map.", genre: 'Arcade', tone: 'Battle', mark: 'PA', color: 'youtube', path: '/games/paper-io-2-3d/index.html', icon: getGameIconUrl('paper-io-2-3d') },
  { id: 'stumble-guys', title: 'Stumble Guys', subtitle: 'Fall, run, win.', description: "Stumble Guys — 32-player knockout chaos, all maps.", genre: 'Arcade', tone: 'Battle', mark: 'SG', color: 'devil', path: '/games/stumble-guys/index.html', icon: getGameIconUrl('stumble-guys') },
  { id: 'dune-dash', title: 'Dune Dash', subtitle: 'Sand sprint.', description: "Desert runner — dash over dunes, dodge rocks. Classroom Center hit.", genre: 'Racing', tone: 'Desert', mark: 'DD', color: 'drive', path: '/games/dune-dash/index.html', icon: getGameIconUrl('dune-dash') },
  { id: 'vibes', title: 'Vibes', subtitle: 'Chill flow.', description: "Vibes — rhythmic dodge, stay in the pulse.", genre: 'Arcade', tone: 'Flow', mark: 'VB', color: 'hextris', path: '/games/vibes/index.html', icon: getGameIconUrl('vibes') },
  { id: 'vortex-tunnel', title: 'Vortex Tunnel', subtitle: 'Spin fast.', description: "Vortex Tunnel — spin through the neon vortex.", genre: 'Arcade', tone: 'Reflex', mark: 'VT', color: 'hextris', path: '/games/vortex-tunnel/index.html', icon: getGameIconUrl('vortex-tunnel') },
  { id: 'rooftop-run', title: 'Rooftop Run', subtitle: 'Parkour above city.', description: "Rooftop Run — jump roofs, don't fall.", genre: 'Platformer', tone: 'Precision', mark: 'RR', color: 'stack', path: '/games/rooftop-run/index.html', icon: getGameIconUrl('rooftop-run') },
  { id: 'hop-fighters', title: 'Hop Fighters', subtitle: 'Hop & punch.', description: "Hop Fighters — hop, kick, K.O.", genre: 'Arcade', tone: 'Battle', mark: 'HF', color: 'devil', path: '/games/hop-fighters/index.html', icon: getGameIconUrl('hop-fighters') },
  { id: 'first-aarc', title: 'First Aarc', subtitle: 'Aim true.', description: "First Aarc — bow aim, hit targets.", genre: 'Arcade', tone: 'Precision', mark: 'FA', color: 'mining', path: '/games/first-aarc/index.html', icon: getGameIconUrl('first-aarc') },
  { id: 'baseball-bros', title: 'Baseball Bros', subtitle: 'Hit homers.', description: "Baseball Bros — swing, hit, run bases.", genre: 'Arcade', tone: 'Sports', mark: 'BB', color: 'drive', path: '/games/baseball-bros/index.html', icon: getGameIconUrl('baseball-bros') },
  { id: 'pumpkill-64', title: 'Pumpkill 64', subtitle: 'Spooky hunt.', description: "Pumpkill 64 — collect pumpkins, avoid ghosts.", genre: 'Arcade', tone: 'Horror', mark: 'PK', color: 'twenty', path: '/games/pumpkill-64/index.html', icon: getGameIconUrl('pumpkill-64') },
  { id: 'gta-simulator', title: 'GTA Simulator', subtitle: 'City free roam.', description: "GTA Simulator — drive, drift, evade.", genre: 'Racing', tone: 'Urban', mark: 'GT', color: 'twenty', path: '/games/gta-simulator/index.html', icon: getGameIconUrl('gta-simulator') },
  { id: 'gunspin', title: 'Gunspin', subtitle: 'Spin to win.', description: "Gunspin — shoot recoil to fly.", genre: 'Arcade', tone: 'Physics', mark: 'GS', color: 'devil', path: '/games/gunspin/index.html', icon: getGameIconUrl('gunspin') },
  { id: 'football-bros', title: 'Football Bros', subtitle: 'Score goals.', description: "Football Bros — pass, shoot, score.", genre: 'Arcade', tone: 'Sports', mark: 'FB', color: 'mining', path: '/games/football-bros/index.html', icon: getGameIconUrl('football-bros') },
  { id: 'steep-descent', title: 'Steep Descent', subtitle: 'Downhill rush.', description: "Steep Descent — ski steep, dodge trees.", genre: 'Racing', tone: 'Snow', mark: 'SD', color: 'hextris', path: '/games/steep-descent/index.html', icon: getGameIconUrl('steep-descent') },
  { id: 'steal-brainrot', title: 'Steal Brainrot', subtitle: 'Meme chaos.', description: "Steal Brainrot — collect memes, avoid brainrot.", genre: 'Arcade', tone: 'Chaos', mark: 'SB', color: 'youtube', path: '/games/steal-brainrot/index.html', icon: getGameIconUrl('steal-brainrot') },
  { id: 'rocket-goal-io', title: 'Rocket Goal', subtitle: 'Boost & score.', description: "Rocket Goal — boost cars, score goals.", genre: 'Arcade', tone: 'Sports', mark: 'RG', color: 'drive', path: '/games/rocket-goal-io/index.html', icon: getGameIconUrl('rocket-goal-io') },
  { id: 'they-are-coming', title: 'They Are Coming', subtitle: 'Survive horde.', description: "They Are Coming — survive zombie horde.", genre: 'Arcade', tone: 'Horror', mark: 'TA', color: 'twenty', path: '/games/they-are-coming/index.html', icon: getGameIconUrl('they-are-coming') },
  { id: 'drift-race', title: 'Drift Race', subtitle: 'Slide corners.', description: "Drift Race — drift through neon city.", genre: 'Racing', tone: 'Drift', mark: 'DR', color: 'drive', path: '/games/drift-race/index.html', icon: getGameIconUrl('drift-race') },
  { id: 'sandbox', title: 'Sandbox', subtitle: 'Build anything.', description: "Sandbox — place blocks, build worlds.", genre: 'Sandbox', tone: 'Creative', mark: 'SB', color: 'mining', path: '/games/sandbox/index.html', icon: getGameIconUrl('sandbox') },
  { id: 'crazy-crash-landing', title: 'Crazy Crash', subtitle: 'Crash safely?', description: "Crazy Crash Landing — steer, land, survive.", genre: 'Arcade', tone: 'Chaos', mark: 'CC', color: 'devil', path: '/games/crazy-crash-landing/index.html', icon: getGameIconUrl('crazy-crash-landing') },
  { id: 'car-simulator', title: 'Car Simulator', subtitle: 'Drive free.', description: "Car Simulator — open world drive.", genre: 'Racing', tone: 'Sim', mark: 'CS', color: 'drive', path: '/games/car-simulator/index.html', icon: getGameIconUrl('car-simulator') },
  { id: 'monster-truck', title: 'Monster Truck', subtitle: 'Crush cars.', description: "Monster Truck — crush, jump, win.", genre: 'Racing', tone: 'Crush', mark: 'MT', color: 'devil', path: '/games/monster-truck/index.html', icon: getGameIconUrl('monster-truck') },
  { id: 'cyber-cars', title: 'Cyber Cars', subtitle: 'Neon race.', description: "Cyber Cars — futuristic neon racing.", genre: 'Racing', tone: 'Neon', mark: 'CC', color: 'hextris', path: '/games/cyber-cars/index.html', icon: getGameIconUrl('cyber-cars') },
  { id: 'volley-random', title: 'Volley Random', subtitle: 'Wobbly volley.', description: "Volley Random — floppy volleyball to 5.", genre: 'Arcade', tone: 'Chaos', mark: 'VR', color: 'stack', path: '/games/volley-random/index.html', icon: getGameIconUrl('volley-random') },
  { id: 'soccer-random', title: 'Soccer Random', subtitle: 'Floppy football.', description: "Soccer Random — wobbly soccer chaos.", genre: 'Arcade', tone: 'Chaos', mark: 'SR', color: 'drive', path: '/games/soccer-random/index.html', icon: getGameIconUrl('soccer-random') },
  { id: 'dash-arena', title: 'Dash Arena', subtitle: 'Dash battle.', description: "Dash Arena — dash, bump, last stand.", genre: 'Arcade', tone: 'Battle', mark: 'DA', color: 'youtube', path: '/games/dash-arena/index.html', icon: getGameIconUrl('dash-arena') },
  { id: 'stick-war', title: 'Stick War', subtitle: 'Command stick.', description: "Stick War — command army, win war.", genre: 'Arcade', tone: 'Strategy', mark: 'SW', color: 'stack', path: '/games/stick-war/index.html', icon: getGameIconUrl('stick-war') },
  { id: 'real-car-driving', title: 'Real Car Driving', subtitle: 'Real physics.', description: "Real Car Driving — realistic drive.", genre: 'Racing', tone: 'Sim', mark: 'RC', color: 'drive', path: '/games/real-car-driving/index.html', icon: getGameIconUrl('real-car-driving') },
  { id: 'drive-online', title: 'Drive Online', subtitle: 'Multiplayer drive.', description: "Drive Online — cruise with friends.", genre: 'Racing', tone: 'Social', mark: 'DO', color: 'drive', path: '/games/drive-online/index.html', icon: getGameIconUrl('drive-online') },
  { id: 'extreme-racing', title: 'Extreme Racing', subtitle: 'Extreme speed.', description: "Extreme Racing — nitro, jump, win.", genre: 'Racing', tone: 'Reflex', mark: 'ER', color: 'devil', path: '/games/extreme-racing/index.html', icon: getGameIconUrl('extreme-racing') },
  { id: 'monster-survival', title: 'Monster Survival', subtitle: 'Survive night.', description: "Monster Survival — survive monsters.", genre: 'Arcade', tone: 'Horror', mark: 'MS', color: 'twenty', path: '/games/monster-survival/index.html', icon: getGameIconUrl('monster-survival') },
  { id: 'obby-shooter', title: 'Obby Shooter', subtitle: 'Obby + gun.', description: "Obby Shooter — parkour and shoot.", genre: 'Arcade', tone: 'Battle', mark: 'OS', color: 'devil', path: '/games/obby-shooter/index.html', icon: getGameIconUrl('obby-shooter') },
  { id: 'helix-jump', title: 'Helix Jump', subtitle: 'Fall through.', description: "Helix Jump — drop ball through helix.", genre: 'Arcade', tone: 'Reflex', mark: 'HJ', color: 'hextris', path: '/games/helix-jump/index.html', icon: getGameIconUrl('helix-jump') },
  { id: 'ninja-parkour', title: 'Ninja Parkour', subtitle: 'Wall run.', description: "Ninja Parkour — wall run, leap.", genre: 'Platformer', tone: 'Precision', mark: 'NP', color: 'stack', path: '/games/ninja-parkour/index.html', icon: getGameIconUrl('ninja-parkour') },
  { id: 'color-puzzle', title: 'Color Puzzle', subtitle: 'Sort colors.', description: "Color Puzzle — sort tubes by color.", genre: 'Puzzle', tone: 'Brain', mark: 'CP', color: 'hextris', path: '/games/color-puzzle/index.html', icon: getGameIconUrl('color-puzzle') },
  { id: 'red-vs-blue', title: 'Red vs Blue', subtitle: 'Team battle.', description: "Red vs Blue — battle arena.", genre: 'Arcade', tone: 'Battle', mark: 'RB', color: 'devil', path: '/games/red-vs-blue/index.html', icon: getGameIconUrl('red-vs-blue') },
  { id: 'build-defend', title: 'Build & Defend', subtitle: 'Build base.', description: "Build & Defend — build, defend wave.", genre: 'Sandbox', tone: 'Strategy', mark: 'BD', color: 'mining', path: '/games/build-defend/index.html', icon: getGameIconUrl('build-defend') },
  { id: 'basket-bros', title: 'Basket Bros', subtitle: 'Dunk duel.', description: "Basket Bros — 2P basketball chaos.", genre: 'Arcade', tone: 'Sports', mark: 'BB', color: 'drive', path: '/games/basket-bros/index.html', icon: getGameIconUrl('basket-bros') },
  { id: 'bad-simulator', title: 'Bad Simulator', subtitle: 'Be bad.', description: "Bad Simulator — cause chaos.", genre: 'Arcade', tone: 'Chaos', mark: 'BS', color: 'twenty', path: '/games/bad-simulator/index.html', icon: getGameIconUrl('bad-simulator') },
  { id: 'war-the-knights', title: 'War The Knights', subtitle: 'Knight war.', description: "War The Knights — slash, defend castle.", genre: 'Arcade', tone: 'Battle', mark: 'WK', color: 'devil', path: '/games/war-the-knights/index.html', icon: getGameIconUrl('war-the-knights') },
  { id: 'raven-shooting', title: 'Raven Shooting', subtitle: 'Shoot ravens.', description: "Raven Shooting — aim, shoot ravens.", genre: 'Arcade', tone: 'Aim', mark: 'RS', color: 'stack', path: '/games/raven-shooting/index.html', icon: getGameIconUrl('raven-shooting') },
  { id: 'ks2-cs', title: 'KS2 CS', subtitle: 'Tactical shoot.', description: "KS2 CS — tactical shooter.", genre: 'Arcade', tone: 'Battle', mark: 'CS', color: 'stack', path: '/games/ks2-cs/index.html', icon: getGameIconUrl('ks2-cs') },
  { id: 'cb-clicker', title: 'CB Clicker', subtitle: 'Click billions.', description: "CB Clicker — click to billions.", genre: 'Idle', tone: 'Clicker', mark: 'CB', color: 'cookie', path: '/games/cb-clicker/index.html', icon: getGameIconUrl('cb-clicker') },
  { id: 'moto-x3m-winter', title: 'Moto X3M Winter', subtitle: 'Icy stunts.', description: "Moto X3M Winter — icy stunt racing.", genre: 'Racing', tone: 'Winter', mark: 'MX', color: 'hextris', path: '/games/moto-x3m-winter/index.html', icon: getGameIconUrl('moto-x3m-winter') },
  { id: 'a-small-world-cup', title: 'A Small World Cup', subtitle: 'Tap-timing soccer', description: "Tap to shoot, bend, score — physics cup. 6X classic.", genre: 'Arcade', tone: 'Sports', mark: 'SW', color: 'drive', path: '/games/a-small-world-cup/index.html', icon: getGameIconUrl('a-small-world-cup') },
  { id: 'bitlife-simulator', title: 'BitLife Simulator', subtitle: 'Live a life', description: "Choose paths — jobs, crime, wealth. Full sim.", genre: 'Simulation', tone: 'Life', mark: 'BL', color: 'mining', path: '/games/bitlife-simulator/index.html', icon: getGameIconUrl('bitlife-simulator') },
  { id: 'big-tower-tiny-square', title: 'Big Tower Tiny Square', subtitle: 'Precision parkour', description: "Tiny square, huge tower — wall-jump perfection.", genre: 'Platformer', tone: 'Precision', mark: 'BT', color: 'stack', path: '/games/big-tower-tiny-square/index.html', icon: getGameIconUrl('big-tower-tiny-square') },
  { id: 'house-of-hazards', title: 'House of Hazards', subtitle: 'Home chaos', description: "House tasks while others sabotage — couch co-op.", genre: 'Arcade', tone: 'Chaos', mark: 'HH', color: 'twenty', path: '/games/house-of-hazards/index.html', icon: getGameIconUrl('house-of-hazards') },
  { id: 'ball-blast', title: 'Ball Blast', subtitle: 'Blast numbers', description: "Shoot cannon, pop falling numbered balls.", genre: 'Arcade', tone: 'Reflex', mark: 'BB', color: 'hextris', path: '/games/ball-blast/index.html', icon: getGameIconUrl('ball-blast') },
  { id: 'rocket-league-2d', title: 'Rocket League 2D', subtitle: 'Car soccer', description: "Drive, jump, boost — score in 2D arena.", genre: 'Arcade', tone: 'Sports', mark: 'RL', color: 'drive', path: '/games/rocket-league-2d/index.html', icon: getGameIconUrl('rocket-league-2d') },
  { id: 'vex-6', title: 'Vex 6', subtitle: 'Parkour 6', description: "The hardest Vex — lasers, saws, new acts.", genre: 'Platformer', tone: 'Hardcore', mark: 'V6', color: 'stack', path: '/games/vex-6/index.html', icon: getGameIconUrl('vex-6') },
  { id: 'noob-survival', title: 'Noob Survival', subtitle: 'Craft & survive', description: "Noob vs zombies — mine, craft, shelter.", genre: 'Sandbox', tone: 'Survival', mark: 'NS', color: 'mining', path: '/games/noob-survival/index.html', icon: getGameIconUrl('noob-survival') },
  { id: 'car-king-arena-2', title: 'Car King Arena 2', subtitle: 'Arena smash', description: "Arena cars — smash, stunt, collect.", genre: 'Racing', tone: 'Arena', mark: 'CK', color: 'drive', path: '/games/car-king-arena-2/index.html', icon: getGameIconUrl('car-king-arena-2') },
  { id: 'basketball-physics', title: 'Basketball Physics', subtitle: 'Ragdoll hoops', description: "Ragdoll 2P — floppy shots to 11.", genre: 'Arcade', tone: 'Sports', mark: 'BP', color: 'drive', path: '/games/basketball-physics/index.html', icon: getGameIconUrl('basketball-physics') },
  { id: '12-minibattles', title: '12 MiniBattles', subtitle: 'Party mayhem', description: "12 silly 2P battles — thumb war to roto.", genre: 'Arcade', tone: 'Party', mark: '12', color: 'youtube', path: '/games/12-minibattles/index.html', icon: getGameIconUrl('12-minibattles') },
  { id: 'miner-dash', title: 'Miner Dash', subtitle: 'Dash & dig', description: "Dash, dig, dodge lava in caves.", genre: 'Platformer', tone: 'Reflex', mark: 'MD', color: 'mining', path: '/games/miner-dash/index.html', icon: getGameIconUrl('miner-dash') },
  { id: 'draw-climber', title: 'Draw Climber', subtitle: 'Draw legs', description: "Draw legs to climb walls — creative climb.", genre: 'Arcade', tone: 'Creative', mark: 'DC', color: 'stack', path: '/games/draw-climber/index.html', icon: getGameIconUrl('draw-climber') },
  { id: 'car-crash-test', title: 'Car Crash Test', subtitle: 'Wreck it', description: "Launch cars, crash, ragdoll physics.", genre: 'Simulation', tone: 'Crash', mark: 'CT', color: 'devil', path: '/games/car-crash-test/index.html', icon: getGameIconUrl('car-crash-test') },
  { id: 'geometry-rash', title: 'Geometry Rash', subtitle: 'Rhythm rush', description: "One-button rash — jump, fly, wave to beat.", genre: 'Rhythm', tone: 'Wave', mark: 'GR', color: 'cookie', path: '/games/geometry-rash/index.html', icon: getGameIconUrl('geometry-rash') },
  { id: 'escape-masters', title: 'Escape Masters', subtitle: 'Escape puzzle', description: "Escape rooms — find keys, codes, doors.", genre: 'Puzzle', tone: 'Escape', mark: 'EM', color: 'hextris', path: '/games/escape-masters/index.html', icon: getGameIconUrl('escape-masters') },
  { id: 'fall-guys', title: 'Fall Guys', subtitle: 'Wobbly race', description: "Wobbly race — 32 knock-out, final crown.", genre: 'Arcade', tone: 'Party', mark: 'FG', color: 'youtube', path: '/games/fall-guys/index.html', icon: getGameIconUrl('fall-guys') },
  { id: 'paper-minecraft', title: 'Paper Minecraft', subtitle: '2D craft', description: "Paper Minecraft — mine, craft, build 2D.", genre: 'Sandbox', tone: 'Craft', mark: 'PM', color: 'mining', path: '/games/paper-minecraft/index.html', icon: getGameIconUrl('paper-minecraft') },
  { id: 'gold-miner', title: 'Gold Miner', subtitle: 'Hook gold', description: "Swing hook, grab gold, avoid rocks.", genre: 'Arcade', tone: 'Physics', mark: 'GM', color: 'cookie', path: '/games/gold-miner/index.html', icon: getGameIconUrl('gold-miner') },
  { id: 'grindcraft-remastered', title: 'Grindcraft Remastered', subtitle: 'Grind & craft', description: "Chop, mine, craft tools — prestige.", genre: 'Idle', tone: 'Craft', mark: 'GC', color: 'mining', path: '/games/grindcraft-remastered/index.html', icon: getGameIconUrl('grindcraft-remastered') },
  { id: 'happy-glass', title: 'Happy Glass', subtitle: 'Draw water', description: "Draw lines to fill glass — pour physics.", genre: 'Puzzle', tone: 'Physics', mark: 'HG', color: 'cookie', path: '/games/happy-glass/index.html', icon: getGameIconUrl('happy-glass') },
  { id: 'snowball-io', title: 'Snowball.io', subtitle: 'Roll & push', description: "Roll snowball, push foes off arena.", genre: 'Arcade', tone: 'Battle', mark: 'SI', color: 'hextris', path: '/games/snowball-io/index.html', icon: getGameIconUrl('snowball-io') },
  { id: 'jelly-truck', title: 'Jelly Truck', subtitle: 'Wobbly drive', description: "Jelly truck — soft-body drive, deliver.", genre: 'Racing', tone: 'Physics', mark: 'JT', color: 'drive', path: '/games/jelly-truck/index.html', icon: getGameIconUrl('jelly-truck') },
  { id: 'short-life', title: 'Short Life', subtitle: 'Ragdoll pain', description: "Dodge saws, spikes — survive office.", genre: 'Arcade', tone: 'Ragdoll', mark: 'SL', color: 'devil', path: '/games/short-life/index.html', icon: getGameIconUrl('short-life') },
  { id: 'minecraft-skyblock', title: 'Minecraft Skyblock', subtitle: 'Sky block', description: "Skyblock — one block expands to island.", genre: 'Sandbox', tone: 'Craft', mark: 'MS', color: 'mining', path: '/games/minecraft-skyblock/index.html', icon: getGameIconUrl('minecraft-skyblock') },
  { id: 'tower-defense', title: 'Tower Defense', subtitle: 'Defend path', description: "Place towers, stop waves — upgrade.", genre: 'Strategy', tone: 'Defense', mark: 'TD', color: 'stack', path: '/games/tower-defense/index.html', icon: getGameIconUrl('tower-defense') },
  { id: 'mr-bullet', title: 'Mr Bullet', subtitle: 'Trick shots', description: "Ricochet bullets — puzzles to kill.", genre: 'Puzzle', tone: 'Aim', mark: 'MB', color: 'devil', path: '/games/mr-bullet/index.html', icon: getGameIconUrl('mr-bullet') },
  { id: 'stick-archers-battle', title: 'Stick Archers Battle', subtitle: 'Archery duel', description: "Aim wind, headshot stick archers.", genre: 'Arcade', tone: 'Aim', mark: 'SA', color: 'stack', path: '/games/stick-archers-battle/index.html', icon: getGameIconUrl('stick-archers-battle') },
  { id: 'swords-and-sandals', title: 'Swords & Sandals', subtitle: 'Gladiator', description: "Gladiator fights — upgrade gear, arena.", genre: 'Arcade', tone: 'Battle', mark: 'SS', color: 'devil', path: '/games/swords-and-sandals/index.html', icon: getGameIconUrl('swords-and-sandals') },
  { id: 'sling-drift', title: 'Sling Drift', subtitle: 'Drift sling', description: "Hold to sling drift — never brake.", genre: 'Racing', tone: 'Drift', mark: 'SD', color: 'drive', path: '/games/sling-drift/index.html', icon: getGameIconUrl('sling-drift') },
  { id: 'piano-tiles', title: 'Piano Tiles', subtitle: 'Tap black', description: "Tap black tiles, avoid white — speed.", genre: 'Rhythm', tone: 'Tap', mark: 'PT', color: 'hextris', path: '/games/piano-tiles/index.html', icon: getGameIconUrl('piano-tiles') },
  { id: 'wheelie-bike', title: 'Wheelie Bike', subtitle: 'Wheelie only', description: "Hold wheelie, balance, collect.", genre: 'Racing', tone: 'Balance', mark: 'WB', color: 'drive', path: '/games/wheelie-bike/index.html', icon: getGameIconUrl('wheelie-bike') },
  { id: 'pixel-shooter', title: 'Pixel Shooter', subtitle: 'Pixel FPS', description: "Pixel shooter — blocky war, online.", genre: 'Shooter', tone: 'FPS', mark: 'PS', color: 'stack', path: '/games/pixel-shooter/index.html', icon: getGameIconUrl('pixel-shooter') },
  { id: 'qwop', title: 'QWOP', subtitle: 'Run cursed', description: "QWOP — run 100m with QWOP keys.", genre: 'Arcade', tone: 'Ragdoll', mark: 'QW', color: 'devil', path: '/games/qwop/index.html', icon: getGameIconUrl('qwop') },
  { id: 'dune-surfer', title: 'Dune Surfer', subtitle: 'Surf dunes', description: "Surf dunes, grind, flip — desert.", genre: 'Racing', tone: 'Surf', mark: 'DS', color: 'hextris', path: '/games/dune-surfer/index.html', icon: getGameIconUrl('dune-surfer') },
  { id: 'the-final-earth-2', title: 'The Final Earth 2', subtitle: 'City in space', description: "Build colony on tiny world — space city.", genre: 'Simulation', tone: 'City', mark: 'FE', color: 'mining', path: '/games/the-final-earth-2/index.html', icon: getGameIconUrl('the-final-earth-2') },
  { id: 'uno', title: 'Uno', subtitle: 'Card classic', description: "Uno — match color/number, +4 win.", genre: 'Puzzle', tone: 'Cards', mark: 'UN', color: 'cookie', path: '/games/uno/index.html', icon: getGameIconUrl('uno') },
  { id: 'sonic-the-hedgehog', title: 'Sonic Hedgehog', subtitle: 'Speed run', description: "Sonic — loops, rings, chaos.", genre: 'Platformer', tone: 'Speed', mark: 'SO', color: 'devil', path: '/games/sonic-the-hedgehog/index.html', icon: getGameIconUrl('sonic-the-hedgehog') },
  { id: 'there-is-no-game', title: 'There Is No Game', subtitle: 'Meta puzzle', description: "Narrator says there is no game — break it.", genre: 'Puzzle', tone: 'Meta', mark: 'NG', color: 'stack', path: '/games/there-is-no-game/index.html', icon: getGameIconUrl('there-is-no-game') },
  { id: 'zombie-outbreak-arena', title: 'Zombie Outbreak Arena', subtitle: 'Survive horde', description: "Horde arena — shoot, loot, survive.", genre: 'Shooter', tone: 'Survival', mark: 'ZO', color: 'twenty', path: '/games/zombie-outbreak-arena/index.html', icon: getGameIconUrl('zombie-outbreak-arena') },
  { id: 'one-escape', title: 'One Escape', subtitle: 'Stealth prison', description: "Stealth escape — guards, keys, vents.", genre: 'Puzzle', tone: 'Stealth', mark: 'OE', color: 'stack', path: '/games/one-escape/index.html', icon: getGameIconUrl('one-escape') },
  { id: 'run-rabbit-run', title: 'Run Rabbit Run', subtitle: 'Carrot chase', description: "Rabbit run — forest dash, carrots.", genre: 'Platformer', tone: 'Runner', mark: 'RR', color: 'cookie', path: '/games/run-rabbit-run/index.html', icon: getGameIconUrl('run-rabbit-run') },
  { id: 'car-driving', title: 'Car Driving', subtitle: 'City drive', description: "City driving — traffic, park.", genre: 'Racing', tone: 'Sim', mark: 'CD', color: 'drive', path: '/games/car-driving/index.html', icon: getGameIconUrl('car-driving') },
  { id: 'short-ride', title: 'Short Ride', subtitle: 'Bike pain', description: "Bike through pain parkour — saws.", genre: 'Racing', tone: 'Ragdoll', mark: 'SR', color: 'devil', path: '/games/short-ride/index.html', icon: getGameIconUrl('short-ride') },
  { id: 'the-little-giant', title: 'The Little Giant', subtitle: 'Grow giant', description: "Twin-stick — stomp, grow bigger.", genre: 'Arcade', tone: 'Grow', mark: 'LG', color: 'stack', path: '/games/the-little-giant/index.html', icon: getGameIconUrl('the-little-giant') },
  { id: 'swerve', title: 'SWERVE', subtitle: 'Swerve pad', description: "Swerve, collect, stay on track.", genre: 'Arcade', tone: 'Reflex', mark: 'SW', color: 'hextris', path: '/games/swerve/index.html', icon: getGameIconUrl('swerve') },
]

export const filters = ['All games', 'Idle', 'Arcade', 'Puzzle', 'Racing', 'Platformer', 'Simulation', 'Sandbox', 'Community', 'Battle', 'Favorites']
export const pubColors = ['cookie', 'drive', 'mining', 'devil', 'stack', 'hextris', 'twenty', 'youtube']
export const FEATURED_IDS = ['cookie-clicker','stack','drive-mad','moto-x3m','among-us','retro-bowl','hole-io']
export const STAFF_PICKS = ['cookie-clicker','retro-bowl','among-us','stack','hole-io','moto-x3m','drive-mad','vortex-tunnel']
export const LOW_QUALITY_HINTS = new Set(['spiral-roll','shape-transform','mr-dude','obby-snowboard','spiders','summer','real-pool-3d','gta-mods','cheese-chompers-3d','flashtetris','bad-ice-cream-2','slope-ball'])
export const CONTROLS_LEGEND: Record<string,string> = {
  Arcade: 'Arrows / WASD to move • Space to jump/action • R to restart',
  Platformer: 'Arrows / WASD • Space to jump • Shift to run • R to restart',
  Racing: 'Arrows / WASD to steer • Space to brake • R to reset',
  Puzzle: 'Mouse + keyboard • Arrows to move • R/Enter to restart',
  Idle: 'Mouse clicks • Space to speed',
  Simulation: 'Mouse + WASD • Scroll to zoom',
  Sandbox: 'WASD to move • Space to jump • E to interact',
  Battle: 'WASD to move • Mouse to aim • Space/Click to shoot',
  Community: 'WASD / Arrows • Space • Enter',
  default: 'Arrows / WASD • Space • Enter • R to restart'
}
export function hashDay(str:string){ let h=0; for(let i=0;i<str.length;i++) h=(h*31+str.charCodeAt(i))>>>0; return h }
export function gameOfDayIndex(len:number, dateStr?:string){ const d=dateStr|| new Date().toISOString().slice(0,10); return hashDay(d)%len }
export const PROXY_TILES = [
  { id:'yt', label:'YouTube', sub:'Watch unblocked', href:'/proxy', icon:'▶', color:'#ff2e63', url:'https://www.youtube.com' },
  { id:'gg', label:'Google', sub:'Search anything', href:'/proxy', icon:'G', color:'#4285f4', url:'https://www.google.com' },
  { id:'dc', label:'Discord', sub:'Chat & calls', href:'/proxy', icon:'◈', color:'#5865f2', url:'https://discord.com/app' },
  { id:'tk', label:'TikTok', sub:'Shorts feed', href:'/proxy', icon:'♪', color:'#00f2ea', url:'https://www.tiktok.com' },
]
