import { readFile, writeFile, access } from 'node:fs/promises';
import { resolve } from 'node:path';
import ts from 'typescript';
const publicRoot = resolve('public');
const source = await readFile('lib/games.ts', 'utf8');
const ast = ts.createSourceFile('lib/games.ts', source, ts.ScriptTarget.Latest, true);
if (ast.parseDiagnostics.length) throw new Error('Catalog syntax error: ' + ts.flattenDiagnosticMessageText(ast.parseDiagnostics[0].messageText, '\n'));
let entries;
function visit(node) {
  if (ts.isVariableDeclaration(node) && node.name.getText(ast) === 'catalogGames' && node.initializer && ts.isArrayLiteralExpression(node.initializer)) entries = node.initializer.elements;
  ts.forEachChild(node, visit);
}
visit(ast);
if (!entries) throw new Error('The catalogGames array was not found.');
const rows = entries.map(entry => {
  if (!ts.isObjectLiteralExpression(entry)) throw new Error('Game entries must be explicit objects for auditing.');
  const row = {};
  for (const prop of entry.properties) if (ts.isPropertyAssignment(prop) && ts.isStringLiteralLike(prop.initializer)) row[prop.name.getText(ast).replace(/['"]/g, '')] = prop.initializer.text;
  if (!row.id || !row.title || !row.path) throw new Error('A catalog entry is missing its identity or launch path.');
  return row;
});
const exists = async file => { try { await access(file); return true; } catch { return false; } };
const audit = {};
for (const game of rows) {
  const issues = [];
  const entry = resolve(publicRoot, '.' + game.path);
  if (!await exists(entry)) issues.push('Missing local index.html');
  else {
    const html = await readFile(entry, 'utf8');
    if (/data-gg-game-state="missing-assets"/.test(html)) issues.push('Authorized browser build not installed');
    if (/<base\b[^>]+href=["']https?:|document\.write\(['"]<base/i.test(html)) issues.push('Remote CDN loader, not a local game');
    if (/<iframe\b[^>]+src=["'](?:https?:)?\/\//i.test(html)) issues.push('External embed, not local game files');
    for (const [,ref] of html.matchAll(/<script\b[^>]*\bsrc=["']([^"']+)["']/gi)) {
      if (/^(data:|blob:)/i.test(ref)) continue;
      const url = new URL(ref, 'https://local.invalid' + game.path);
      if (url.origin !== 'https://local.invalid') { issues.push('External runtime script: ' + url.hostname); continue; }
      const target = resolve(publicRoot, '.' + decodeURIComponent(url.pathname));
      if (!target.startsWith(publicRoot + '/')) { issues.push('Invalid script path'); continue; }
      if (!await exists(target)) issues.push('Missing runtime: ' + url.pathname);
      else if (/^\s*<(?:!doctype|html)/i.test((await readFile(target,'utf8')).slice(0,200))) issues.push('Runtime contains an HTML error page: ' + url.pathname);
    }
    // Unity's legacy config lists the binaries needed before the first frame.
    for (const [,ref] of html.matchAll(/UnityLoader\.instantiate\(\s*["'][^"']+["']\s*,\s*["']([^"']+\.json)["']/g)) {
      const configUrl = new URL(ref, 'https://local.invalid' + game.path);
      const file = resolve(publicRoot, '.' + decodeURIComponent(configUrl.pathname));
      try {
        const config = JSON.parse(await readFile(file, 'utf8'));
        // WebAssembly builds do not need the obsolete asm.js fallback payloads.
        const keys = config.wasmCodeUrl ? ['dataUrl','wasmCodeUrl','wasmFrameworkUrl'] : ['dataUrl','asmCodeUrl','asmMemoryUrl','asmFrameworkUrl'];
        for (const key of keys) {
          if (typeof config[key] !== 'string' || config[key].startsWith('data:')) continue;
          const asset = new URL(config[key], configUrl);
          if (asset.origin !== configUrl.origin) issues.push('External Unity asset: ' + key);
          else if (!await exists(resolve(publicRoot, '.' + decodeURIComponent(asset.pathname)))) issues.push('Missing Unity asset: ' + asset.pathname);
        }
      } catch { issues.push('Missing or invalid Unity config: ' + ref); }
    }
  }
  audit[game.id] = { available: issues.length === 0, issues: [...new Set(issues)] };
}
await writeFile('lib/game-assets.json', JSON.stringify(audit, null, 2) + '\n');
const missing = rows.filter(game => !audit[game.id].available);
await writeFile('docs/GAME-ASSET-AUDIT.md', '# Game asset audit\n\nGenerated by `npm run audit:games`. This checks entry points, local scripts and legacy Unity payloads; **file presence is not proof of successful gameplay**. Browser smoke tests cover representative engines separately.\n\n' + `${rows.length - missing.length}/${rows.length} catalogue entries have their checked local assets. ${missing.length} need attention and are not advertised as playable.\n\n` + '| Game | Blocker |\n|---|---|\n' + missing.map(game => `| ${game.title} | ${audit[game.id].issues.join('; ')} |`).join('\n') + '\n');
console.log(`Asset audit: ${rows.length - missing.length}/${rows.length} entries with checked local files; ${missing.length} missing/external loaders.`);
